import { WisdomQuote } from './types';

// Danh sách 30 câu châm ngôn Krog Việt Hóa giai đoạn MVP
export const WISDOM_POOL: WisdomQuote[] = [
  { id: 1, content: "Nghĩ nhiều làm đầu krog đau. Làm việc nhỏ trước, đá lớn tự khắc dịch chuyển." },
  { id: 2, content: "Nhìn vào đống lửa của hang người khác không làm hang của bạn ấm lên." },
  { id: 3, content: "Cành củi khô bẻ được hôm nay tốt hơn thân cây cổ thụ to lớn ngày mai." },
  { id: 4, content: "Lo lắng giống sương mù trong rừng. Trông dày đặc nhưng giơ tay ra không bắt được." },
  { id: 5, content: "Ham muốn quá nhiều làm krog nghèo đi. Biết ơn củ khoai đang có làm krog giàu lên." },
  { id: 6, content: "Hôm nay tộc trưởng mắng? Kệ tộc trưởng. Tộc trưởng cũng chỉ là một con krog nhiều việc hơn." },
  { id: 7, content: "Nước chảy đá mòn. Krog không cần vội, krog cứ đi đều bước như rùa rừng." },
  { id: 8, content: "Khoe khoang nhiều vỏ sò không làm krog săn hổ giỏi hơn. Im lặng và mài rìu." },
  { id: 9, content: "Kiếm nhiều đá bóng loáng để làm gì khi lưng krog đau không ngủ được trên thảm cỏ?" },
  { id: 10, content: "Khi tức giận, krog hãy đi dạo quanh gốc cây to 3 vòng. Gốc cây không biết cãi nhau." },
  { id: 11, content: "Mưa bão rồi sẽ tạnh. Hang đá vững chãi luôn đợi krog về ăn khoai nướng." },
  { id: 12, content: "Đừng đếm số quả trên cây khi chưa tự tay leo lên hái." },
  { id: 13, content: "Lỗi lầm hôm qua giống dấu chân trên cát. Sóng vỗ một cái là sạch sẽ." },
  { id: 14, content: "Krog cho đi một miếng thịt hoẵng, lòng krog vui ba ngày. Giữ lại một mình, thịt thối." },
  { id: 15, content: "Bạn tốt là người cùng krog đẩy đá, không phải người đứng ngoài la hét bảo đẩy thế nào." },
  { id: 16, content: "Ngủ một giấc thật sâu. Mọi quỷ dữ trong đầu thường sợ ánh sáng bình minh." },
  { id: 17, content: "Con hổ to nhất cũng có lúc già yếu. Khó khăn lớn mấy rồi cũng qua thời kỳ đỉnh cao." },
  { id: 18, content: "Ăn miếng cơm chậm rãi. Nhai kỹ thấy ngọt. Sống vội vã nuốt cả hạt sỏi." },
  { id: 19, content: "Nghe tiếng chim hót miễn phí. Ngắm trời mây xanh miễn phí. Sao krog cứ buồn vì thứ đắt tiền?" },
  { id: 20, content: "Học hỏi krog già trong bộ tộc. Họ có nhiều sẹo, nghĩa là họ biết cách sống sót." },
  { id: 21, content: "Làm việc mệt thì ngồi nghỉ dưới bóng râm. Đừng ngồi nghỉ dưới trời nắng gắt rồi trách trời nóng." },
  { id: 22, content: "Lời nói ác ý như mũi tên tre bắn vào vách đá. Chỉ tổ gãy mũi tên chứ đá không đau." },
  { id: 23, content: "Trồng một hạt mầm nhỏ, tưới chút nước mỗi ngày. Cây đại thụ không lớn lên trong một đêm." },
  { id: 24, content: "Chia sẻ lửa ấm với người bị lạnh, lửa của krog không hề bớt sáng đi." },
  { id: 25, content: "Đừng cố làm hài lòng tất cả chim muông trong rừng. Krog chỉ cần chim sẻ nhà mình vui." },
  { id: 26, content: "Một ngày không săn được hươu thì hái nấm. Không có thịt thì ăn rau, bụng vẫn no." },
  { id: 27, content: "Sức mạnh của krog nằm ở cánh tay vững chãi, không nằm ở cái bóng to khi nắng xế chiều." },
  { id: 28, content: "Đừng tích trữ quá nhiều củi mục. Hang hẹp mà củi chật thì không còn chỗ nằm ngủ." },
  { id: 29, content: "Biết đủ là đỉnh cao của trí tuệ người tiền sử. Thêm nữa chỉ tổ nặng lưng." },
  { id: 30, content: "Mặt trời luôn mọc ở đằng đông. Hôm nay đen tối, mai trời lại sáng, krog lại đi săn." },
  { id: 31, content: "Nhìn vũng nước mưa thấy mặt mình xấu xí, krog đừng đập vũng nước. Vũng nước không có lỗi." },
  { id: 32, content: "Cây cung căng quá sẽ đứt dây. Krog gồng mình quá sẽ đổ bệnh. Thả lỏng tay ra." },
  { id: 33, content: "Sợ hãi hươu cao cổ vì cổ nó dài? Krog cứ đứng dưới đất ăn cỏ, nó không cúi xuống cắn krog đâu." },
  { id: 34, content: "Mượn rìu đá của người khác nhớ trả sớm. Lần sau hang krog cháy, họ mới mang nước qua cứu." },
  { id: 35, content: "Con suối nhỏ quanh co chảy mãi rồi cũng ra sông lớn. Krog đi chậm nhưng không dừng là được." },
  { id: 36, content: "Krog chê củ khoai méo mó? Khi đói, khoai méo hay khoai tròn đều làm bụng krog ngừng kêu." },
  { id: 37, content: "Kẻ nói xấu sau lưng krog là kẻ luôn đi sau krog. Người đi trước bận nhìn đường săn hoẵng." },
  { id: 38, content: "Nhặt một viên sỏi đẹp cất vào túi, lòng vui cả ngày. Hạnh phúc của krog rẻ hơn krog tưởng." },
  { id: 39, content: "Đừng cười krog khác vấp ngã. Đường rừng nhiều rễ cây, tí nữa đến lượt krog đấy." },
  { id: 40, content: "Răng rụng thì ăn cháo khoai. Mắt mờ thì nghe chim hót. Thời nào cũng có cái sướng của nó." },
  { id: 41, content: "Hang to mà lạnh lẽo không bằng lều cỏ mà ấm áp khói bay." },
  { id: 42, content: "Bão đêm qua quật đổ cây cổ thụ, nhưng bụi cỏ ven đường vẫn xanh. Mềm mại đôi khi sống dai hơn cứng nhắc." },
  { id: 43, content: "Krog muốn hái quả ngọt trên ngọn cây cao? Học cách ngã vài lần đau mông trước đã." },
  { id: 44, content: "Tranh cãi với con vẹt rừng chỉ làm krog mỏi họng. Con vẹt chỉ nói lại những gì nó nghe, không có não." },
  { id: 45, content: "Ăn quả vả rừng nhớ ơn người trồng cây. Ăn thịt hoẵng nhớ ơn người mài rìu." },
  { id: 46, content: "Túi da báo rách có thể khâu lại bằng gân thú. Lòng tin vỡ rồi, khâu lại vẫn đầy sẹo." },
  { id: 47, content: "Thấy người khác săn được voi, krog đừng vội nản lòng. Voi to thì khó khiêng, hoẵng nhỏ vừa miếng ăn." },
  { id: 48, content: "Đom đóm lập lòe không thắp sáng được hang, nhưng làm đêm tối bớt đáng sợ. Việc tốt nhỏ cũng vậy." },
  { id: 49, content: "Trời mưa thì trú hang. Trời nắng thì phơi váy vỏ cây. Thuận theo ông trời, krog sống thọ." },
  { id: 50, content: "Cái bụng đói là người thầy tốt nhất. Nó dạy krog biết giá trị của một hạt ngô rơi." },
  { id: 51, content: "Đừng đem cá lên bờ dạy nó leo cây. Đừng bắt krog thích vẽ tranh phải đi săn hổ giỏi." },
  { id: 52, content: "Krog ghen tị với bộ lông của con công? Công đẹp nhưng thịt dai, chẳng béo bở gì." },
  { id: 53, content: "Đá nhọn làm đau chân krog, nhưng nhờ nó mà krog biết nhìn xuống đường khi đi." },
  { id: 54, content: "Ngồi một chỗ than vãn không làm củi tự khô. Nhấc mông lên và mang ra phơi nắng." },
  { id: 55, content: "Lời nói dịu dàng như gió mùa xuân, làm tan băng tuyết trong lòng krog khác." },
  { id: 56, content: "Khoe cây gậy to không làm krog mạnh hơn. Sức mạnh nằm ở cái đầu biết né bẫy thú." },
  { id: 57, content: "Chê bai dòng suối đục hôm nay? Ngày mai nắng hạn, nước đục krog cũng thèm." },
  { id: 58, content: "Con ong chăm chỉ hút mật hoa, không bận tâm con ruồi bay quanh đống phân. Krog hãy làm ong." },
  { id: 59, content: "Cơn giận giống như lửa cháy trong tay. Krog định ném vào người khác nhưng krog bị bỏng trước." },
  { id: 60, content: "Mất một cái rìu đá? Coi như cái rìu đó đi tìm chủ mới có duyên hơn. Nghĩ thoáng cho nhẹ đầu." },
  { id: 61, content: "Người khôn ngoan biết lúc nào nên hú lên gọi bầy, lúc nào nên im lặng núp sau bụi rậm." },
  { id: 62, content: "Mùa đông lạnh giá nhắc krog nhớ rằng đốm lửa nhỏ ngày thường đáng quý biết bao." },
  { id: 63, content: "Đừng cố lội qua dòng sông hung dữ khi nước đang cuộn đỏ. Đợi một ngày, nước sẽ tự trong." },
  { id: 64, content: "Vẽ hình con hươu lên vách hang không làm bụng krog no. Phải cầm giáo bước ra ngoài." },
  { id: 65, content: "Krog cười người khác vì họ khác krog? Cả khu rừng có trăm loại lá, loại nào cũng có nét hay." },
  { id: 66, content: "Một cái ôm ấm áp từ krog nhà mình đáng giá hơn mười lời khen sáo rỗng ngoài bờ suối." },
  { id: 67, content: "Đi săn một mình đi nhanh, đi săn cùng bộ tộc đi xa. Muốn bắt voi phải đi đông người." },
  { id: 68, content: "Quá khứ đã qua như tro tàn bếp lửa. Tương lai chưa tới như mầm non dưới đất. Sống cho củ khoai hôm nay." },
  { id: 69, content: "Đừng đổ lỗi cho bóng đêm tối tăm. Hãy tự trách mình chưa chuẩn bị sẵn một bó đuốc." },
  { id: 70, content: "Sông sâu nước chảy lặng lờ. Krog nông nổi thì hay oang oang cái miệng." },
  { id: 71, content: "Nhìn thấy tổ ong mật trên cao? Đừng vội chọc gậy. Hãy chuẩn bị khói để đuổi ong trước." },
  { id: 72, content: "Một lời nói ác ý lúc nóng giận cần mười rổ quả ngọt cũng không bù đắp được." },
  { id: 73, content: "Krog mệt mỏi vì đuổi theo con bướm? Đứng im một lát, hoa nở bướm tự bay đến." },
  { id: 74, content: "Bảo vệ đốm lửa nhỏ của mình trước gió, đừng đi thổi tắt lửa của hang hàng xóm." },
  { id: 75, content: "Trái cây chín ép ăn chát ngắt. Tình cảm vội vàng dễ rạn nứt. Hãy cứ thong thả." },
  { id: 76, content: "Krog có hai tai và một cái miệng. Hãy nghe nhiều hơn gấp đôi số lời krog nói ra." },
  { id: 77, content: "Con khỉ chuyền cành hay ngã vì nó quá tự tin. Krog đi dưới đất cứ cẩn thận từng bước." },
  { id: 78, content: "Đá cuội mịn màng nhờ dòng nước vỗ về nghìn năm. Krog tốt lên nhờ va vấp cuộc đời." },
  { id: 79, content: "Đừng cầu mong khu rừng không có thú dữ. Hãy cầu mong cánh tay krog đủ khỏe để cầm giáo." },
  { id: 80, content: "Nuôi một con chó nhỏ, nó trung thành hơn vạn lời thề non hẹn biển của krog lạ." },
  { id: 81, content: "Thấy trời sập thì có krog cao hơn đỡ. Krog lùn cứ yên tâm ngồi nhai củ mài." },
  { id: 82, content: "Biết ơn con suối cho nước uống, biết ơn mặt trời cho hơi ấm, biết ơn mặt đất cho chỗ ngủ." },
  { id: 83, content: "Kẻ thích chỉ tay năm ngón thường là kẻ không biết cầm rìu đá chặt củi." },
  { id: 84, content: "Học cách từ chối miếng thịt ôi thiu, krog sẽ tránh được cái bụng đau quặn thắt." },
  { id: 85, content: "Một ngày không làm việc gì có ích thì đêm nằm ngủ lưng thấy cộm, lòng thấy bồn chồn." },
  { id: 86, content: "Đừng hứa cho người khác nửa con lợn rừng khi mũi tên của krog còn chưa lắp vào dây cung." },
  { id: 87, content: "Lông chim công đẹp thật, nhưng không giữ ấm được cho krog bằng tấm da gấu xù xì." },
  { id: 88, content: "Khi bộ tộc xảy ra tranh cãi, krog thông minh chọn đi nhặt củi. Vừa được việc vừa đỡ nhức đầu." },
  { id: 89, content: "Con rùa bò chậm nhưng nó ít khi hụt hơi. Krog chạy thục mạng coi chừng ngã gãy răng." },
  { id: 90, content: "Chỉ có krog ngốc mới thử độ sâu của dòng sông bằng cả hai chân." },
  { id: 91, content: "Một đốm lửa nhỏ có thể đốt cháy cả khu rừng. Một lời nói bậy có thể phá nát một bộ tộc." },
  { id: 92, content: "Thấy quả lạ màu sắc sặc sỡ chớ vội ăn. Đẹp đẽ thường đi đôi với kịch độc." },
  { id: 93, content: "Ngã ở đâu thì nằm nghỉ ở đó một lát, nhìn xem có nhặt được viên đá đẹp nào không rồi đứng dậy." },
  { id: 94, content: "Krog gieo hạt gì thì krog hái quả đó. Không thể gieo hạt gai mà đòi hái quả vả ngọt." },
  { id: 95, content: "Mặt trời lặn rồi thì đi ngủ. Đừng cố thức cãi nhau với bóng đêm." },
  { id: 96, content: "Người thật lòng giúp krog thường im lặng làm. Người nói lời hay ho thường biến mất khi bão tới." },
  { id: 97, content: "Bộ lông không làm nên con sếu. Cái rìu tốt không làm nên người thợ săn giỏi." },
  { id: 98, content: "Đừng tiếc nuối con cá sẩy ngoài sông. Con cá nằm trong rổ mới là con cá nuôi sống krog." },
  { id: 99, content: "Mỗi ngày thức dậy thấy mình còn thở, chân còn đi được, tay còn cầm được củ khoai ấy là đại phúc." },
  { id: 100, content: "Trí tuệ của krog già không nằm ở số vỏ sò họ có, mà nằm ở số vết sẹo họ vượt qua." },
  { id: 101, content: "Muốn bắt cá to dưới suối sâu, krog phải học cách đan lưới bằng vỏ cây dai trước đã." },
  { id: 102, content: "Chê bai củ mài nhiều rễ xù xì, krog sẽ phải nhịn đói khi mùa đông tuyết phủ trắng rừng." },
  { id: 103, content: "Mũi tên tre bay nhanh nhờ cánh lông chim, krog làm việc lớn cần bạn tốt đỡ đần." },
  { id: 104, content: "Tiếng hú của con hoẵng trong đêm không làm hang krog sập, đừng tự dọa mình mà mất ngủ." },
  { id: 105, content: "Khoe khoang hình vẽ voi đại ngàn lên vách đá không làm cánh tay krog khỏe thêm một tí nào." },
  { id: 106, content: "Rìu đá cùn thì mài vào đá cuội bên suối, lòng krog nguội thì ngồi cạnh bếp lửa sưởi đêm." },
  { id: 107, content: "Đốm lửa nhỏ giữ được qua đêm đông là nhờ krog biết siêng năng gom củi khô từ chiều." },
  { id: 108, content: "Đừng đứng trên vách đá cao mà chửi bới cơn bão, bão không nghe thấy, krog lại hụt hơi ngã." },
  { id: 109, content: "Con hoẵng nhỏ chạy nhanh mệt chân, củ khoai nằm im dưới đất đào lên ăn béo bụng." },
  { id: 110, content: "Khi bộ tộc ngủ say, đốm lửa vẫn thức canh gác thú dữ. Hãy biết ơn người canh lửa." },
  { id: 111, content: "Krog có thể mất ba ngày để tìm một lối đi qua đầm lầy, còn hơn lao đại xuống rồi chết chìm." },
  { id: 112, content: "Nhìn hạt mưa rơi bạt mạng ngoài cửa hang, krog mới thấy trân trọng mái đá che đầu." },
  { id: 113, content: "Cây gậy tre cong vòng vẫn có thể khều được quả chín, đừng vội vứt bỏ thứ còn dùng được." },
  { id: 114, content: "Học cách nhường lối cho con gấu mẹ đang dẫn con đi, đó không phải hèn nhát mà là khôn ngoan." },
  { id: 115, content: "Một miếng thịt nướng khét vẫn nuôi sống krog qua cơn đói, chớ có kén chọn khi nghèo khó." },
  { id: 116, content: "Vỏ sò lấp lánh dải cát không ăn được, krog đừng đổi cả rổ khoai lấy thứ đồ chơi đó." },
  { id: 117, content: "Gió bão thổi bay mái lá lều cỏ, nhưng không làm lung lay được tấm lòng của krog già." },
  { id: 118, content: "Con chim sẻ nhỏ hót vang mỗi sáng chẳng đòi krog củ khoai nào, sao krog cứ hằn học với nó?" },
  { id: 119, content: "Đôi bàn chân chai sần giúp krog đi qua bãi gai nhọn mà không cần sợ hãi rỉ máu." },
  { id: 120, content: "Tộc trưởng bảo đi hướng đông săn voi, krog thấy hướng tây nhiều nấm thì cứ lặng lẽ hái." },
  { id: 121, content: "Đừng tiếc nuối quả ngọt đã bị khỉ ăn mất, khu rừng rộng lớn còn nhiều bụi cây chín mọng." },
  { id: 122, content: "Khi lòng krog rối như mớ dây bện, hãy ngồi xuống bờ suối nhìn nước chảy một canh giờ." },
  { id: 123, content: "Ngọn giáo tốt là ngọn giáo đâm trúng mục tiêu, không phải ngọn giáo có khắc nhiều hoa văn." },
  { id: 124, content: "Krog cho người khác mượn lửa, hang krog không tối đi, mà cả thung lũng sẽ cùng sáng." },
  { id: 125, content: "Nuôi con lợn rừng từ nhỏ thì nó hiền, kết bạn với krog xấu từ đầu thì sớm muộn cũng hại thân." },
  { id: 126, content: "Thấy vách đá nứt thì đừng dại dột dựng lều che nắng dưới chân nó, đá sập không báo trước." },
  { id: 127, content: "Củ mài đắng ăn cùng mật ong rừng sẽ ngọt, khó khăn hôm nay có nụ cười krog nhà mình sẽ qua." },
  { id: 128, content: "Đừng cố đếm xem bầu trời có bao nhiêu ngôi sao, lo đếm xem hang mình còn mấy bó củi khô." },
  { id: 129, content: "Con rùa nhỏ biết thu đầu vào mai khi gặp nguy hiểm, krog bớt cái tôi lại đúng lúc sẽ sống thọ." },
  { id: 130, content: "Tiếng cười vang trong hang đá xua tan mọi bóng ma u ám của mùa đông đói khát." },
  { id: 131, content: "Đập vỡ một hòn đá thạch anh thấy bên trong lấp lánh, con người cũng vậy, nhìn ngoài sao biết được." },
  { id: 132, content: "Đừng bắt con hoẵng phải lội nước giỏi như con cá sấu, mỗi đứa có một giang sơn riêng." },
  { id: 133, content: "Mưa dầm thấm lâu, krog làm việc nhỏ mỗi ngày sẽ tích được đống củi cao bằng đầu." },
  { id: 134, content: "Khi tức giận tộc trưởng, krog hãy đi bẻ củi khô. Vừa xả được giận vừa có lửa sưởi." },
  { id: 135, content: "Con cá sẩy là con cá to, củ khoai rơi mất là củ khoai ngọt, lòng tham luôn làm krog tiếc nuối." },
  { id: 136, content: "Đôi mắt krog nhìn xa được mười dặm nhưng không nhìn thấy hạt bụi đang nằm trong mắt mình." },
  { id: 137, content: "Học hỏi từ vết chân con báo để lại trên bùn, krog sẽ biết hướng nào không nên bước tới." },
  { id: 138, content: "Đừng đem bí mật của hang mình kể cho con vẹt rừng, nó sẽ hét lên cho cả bộ tộc nghe thấy." },
  { id: 139, content: "Tấm da hổ đẹp chỉ thuộc về thợ săn dũng cảm chịu nằm sương nếm mật ba đêm ngoài rừng rậm." },
  { id: 140, content: "Một lời khen chân thành làm krog ấm lòng hơn cả một tấm da thú dày mùa giá rét." },
  { id: 141, content: "Đừng chê vách hang thô ráp, bão nổi lên mới biết nó vững chãi hơn trăm lều cỏ bện." },
  { id: 142, content: "Con sóc nhỏ lo tích hạt dẻ từ mùa thu, krog lười biếng mùa hè thì mùa đông nhai rễ cây." },
  { id: 143, content: "Nếu chân krog ngắn, đừng cố nhảy qua rãnh sâu, hãy tìm một khúc gỗ mục bắc cầu mà đi." },
  { id: 144, content: "Tranh giành một vỏ sò đẹp làm rạn nứt tình huynh đệ đẩy đá cùng nhau bao năm qua." },
  { id: 145, content: "Lửa cháy to quá dễ làm cháy cả lều, lòng nhiệt tình quá mức đôi khi làm người khác hoảng sợ." },
  { id: 146, content: "Khi trời tối, mọi con đường rừng đều giống nhau, krog khôn ngoan chọn ngồi im chờ bình minh." },
  { id: 147, content: "Ăn nấm độc chết người, nghe lời phao tin nhảm chết cả một dòng tộc, krog phải tỉnh táo." },
  { id: 148, content: "Con cọp già mất nanh vẫn đáng sợ, chớ có dại dột vuốt râu nó khi nó đang nằm ngủ." },
  { id: 149, content: "Một giọt mật ong quý giá hơn cả chum nước lã, một lời nói đúng lúc cứu được một mạng người." },
  { id: 150, content: "Krog thà ngủ trên đất nện ấm áp còn hơn nằm trên giường đá cao mà gió lùa tứ phía." },
  { id: 151, content: "Nhìn thấy khói bay lên từ xa, krog biết nơi đó có đồng loại và sự sống đang tiếp diễn." },
  { id: 152, content: "Đừng hứa dắt người khác đi săn khi chính krog còn chưa biết đường ra khỏi bãi đầm lầy." },
  { id: 153, content: "Cây tre già cho măng ngọt, krog già cho lời khuyên hay, chớ có xem thường người đi trước." },
  { id: 154, content: "Vết thương do gai đâm mau lành, vết thương do lời nói ác độc của bạn thân thì đau cả đời." },
  { id: 155, content: "Thấy người khác có cung tên đẹp, krog đừng ghen tị, cung tốt phụ thuộc vào sức căng cánh tay." },
  { id: 156, content: "Mùa màng thất thu thì trồng khoai bù lại, cuộc đời thất bại thì làm lại từ việc nhỏ nhất." },
  { id: 157, content: "Con chim ưng bay cao nhìn thấu vạn vật, krog ngồi đáy hang chỉ thấy một khoảng trời tròn." },
  { id: 158, content: "Hãy sống giống như dòng suối xuân, mang nước mát cho đời mà không đòi hỏi ai trả ơn." },
  { id: 159, content: "Bắt được con rùa rừng thì nhớ thả con rùa con, để dành cho mùa sau con cháu krog còn có cái ăn." },
  { id: 160, content: "Lời thề thốt khi say rượu cần như bọt nước bờ suối, nắng lên là tan biến không dấu vết." },
  { id: 161, content: "Đừng ngồi đếm vết sẹo trên lưng người khác rồi chê họ vụng về, krog không đi săn sao biết đau." },
  { id: 162, content: "Một hòn đá to cản lối đi, krog thông minh dùng nó làm bệ đỡ để leo lên cao nhìn đường." },
  { id: 163, content: "Cây cung tốt không ở màu sơn, người đàn ông tốt không ở cái miệng dẻo kẹo ngoài bờ suối." },
  { id: 164, content: "Con ong chăm chỉ làm tổ không rảnh để cãi nhau với con muỗi vo ve suốt ngày." },
  { id: 165, content: "Ăn miếng thịt hoẵng dai một chút còn hơn nuốt phải miếng xương cá hóc nghẹn ở cổ." },
  { id: 166, content: "Trời ban cho krog hai mắt để nhìn trước ngó sau, chứ không phải để nhìn chằm chằm vào hang nhà người ta." },
  { id: 167, content: "Khi dòng suối cạn nước, krog mới biết ai là người thật lòng chia sẻ giọt nước cuối cùng." },
  { id: 168, content: "Đừng trách cơn gió làm tắt ngọn đuốc, hãy trách mình không biết dùng tay che chắn cẩn thận." },
  { id: 169, content: "Một ngày không nhặt củi thì mùa đông hang lạnh, một ngày không học hỏi thì cái đầu krog tối tăm." },
  { id: 170, content: "Con báo săn mồi bằng sự im lặng, krog đi làm việc lớn chớ có rêu rao cho cả tổng biết." },
  { id: 171, content: "Củ khoai nướng nóng bỏng tay, krog vội vã cắn một miếng to chỉ tổ phồng mồm trợn mắt." },
  { id: 172, content: "Thấy người ta đổi được nhiều vỏ sò đẹp, krog chớ dại bán đi cây cung nuôi sống gia đình." },
  { id: 173, content: "Bão giông chỉ làm rụng bớt lá vàng, cây cổ thụ vững rễ vẫn xanh tươi khi nắng ấm quay về." },
  { id: 174, content: "Đừng mang con cá lóc lên đỉnh núi bắt nó tập bay, đừng bắt krog yếu tay phải vác rìu tạ." },
  { id: 175, content: "Lòng tham như cái hố không đáy trong hang, krog lấp bao nhiêu thịt hoẵng vào cũng chẳng vừa." },
  { id: 176, content: "Biết ơn vách đá cho chỗ trú chân, biết ơn dòng suối cho ngụm nước mát sảng khoái tâm hồn." },
  { id: 177, content: "Con khỉ chuyền cành hay ngã vì thích trèo cao, krog đi dưới đất cứ thong thả từng bước chắc chắn." },
  { id: 178, content: "Lời nói ác ý giống như mũi tên tre bắn vào vách núi, chỉ tổ gãy mũi tên chứ đá chẳng hề hấn gì." },
  { id: 179, content: "Một đốm lửa nhỏ nhen nhóm từ củi khô có thể thắp sáng cả hang đá u tối suốt mùa đông." },
  { id: 180, content: "Đừng đuổi theo con hươu chạy nhanh nhất rừng, hãy nhắm con hoẵng vừa sức với mũi tên của krog." },
  { id: 181, content: "Khi bộ tộc có biến, krog thông minh chọn cách im lặng mài rìu chứ không đứng hùa theo đám đông." },
  { id: 182, content: "Tấm da thú xù xì giữ ấm tốt hơn vạn lần lông chim công sặc sỡ mà mỏng manh dễ rách." },
  { id: 183, content: "Con rùa bò chậm chạp nhưng nó hiếm khi hụt hơi, krog chạy thục mạng coi chừng vấp đá gãy răng." },
  { id: 184, content: "Chỉ có krog ngốc mới dùng cả hai chân để đo độ sâu của dòng sông đang cuộn chảy xiết." },
  { id: 185, content: "Thấy quả lạ màu sắc sặc sỡ chớ có dại dột hái ăn, cái gì quá đẹp thường chứa kịch độc." },
  { id: 186, content: "Ngã ở đâu thì nằm nghỉ ngơi ở đó một lát, nhìn xem có nhặt được hòn đá đẹp nào không rồi đứng dậy." },
  { id: 187, content: "Krog gieo hạt gì thì krog gặt quả đó, không thể gieo hạt gai mà đòi hái quả vả ngọt lịm." },
  { id: 188, content: "Mặt trời lặn rồi thì krog đi ngủ, đừng cố thức để tranh cãi với bóng đêm làm gì cho mệt." },
  { id: 189, content: "Người thật lòng giúp krog thường im lặng hành động, kẻ nói lời hoa mỹ thường biến mất khi bão tới." },
  { id: 190, content: "Bộ lông không làm nên con sếu kiêu sa, cái rìu đá tốt không làm nên người thợ săn giỏi giang." },
  { id: 191, content: "Đừng tiếc nuối con cá to sẩy ngoài dòng suối, con cá nằm gọn trong rổ mới nuôi sống được krog." },
  { id: 192, content: "Mỗi ngày thức dậy thấy chân còn đi được, tay còn cầm được củ khoai nướng ấy là đại phúc." },
  { id: 193, content: "Trí tuệ của krog già không nằm ở số vỏ sò tích trữ, mà nằm ở số vết sẹo sinh tồn vượt qua." },
  { id: 194, content: "Nhìn vũng nước mưa thấy mặt mình nhem nhuốc, krog đừng đập vũng nước, vũng nước đâu có lỗi gì." },
  { id: 195, content: "Cây cung căng quá sớm muộn sẽ đứt dây, krog gồng mình quá sức sẽ đổ bệnh, hãy thả lỏng ra." },
  { id: 196, content: "Sợ hãi hươu cao cổ vì cổ nó quá dài? Krog cứ đứng dưới đất ăn củ mài, nó chẳng thèm cúi xuống đâu." },
  { id: 197, content: "Mượn rìu đá của hang hàng xóm nhớ trả sớm, lần sau hang krog cháy họ mới mang nước qua cứu giúp." },
  { id: 198, content: "Con suối nhỏ quanh co chảy mãi rồi cũng ra sông lớn, krog đi chậm nhưng không dừng lại là được." },
  { id: 199, content: "Krog chê củ khoai méo mó xấu xí? Khi đói củ khoai nào cũng làm bụng krog ngừng kêu oai oái." },
  { id: 200, content: "Kẻ thích nói xấu sau lưng krog là kẻ luôn đi phía sau krog, người đi trước bận nhìn đường săn hoẵng." },
  { id: 201, content: "Nhặt một viên sỏi đẹp cất vào túi da báo, lòng vui cả ngày, hạnh phúc rẻ hơn krog tưởng nhiều." },
  { id: 202, content: "Đừng cười krog khác vấp ngã rễ cây, đường rừng khúc khuỷu, tí nữa có khi đến lượt krog đấy." },
  { id: 203, content: "Răng rụng thì krog húp cháo khoai mài, mắt mờ thì nghe chim hót, thời nào cũng có cái thú của nó." },
  { id: 204, content: "Hang to rộng mà lạnh lẽo cô đơn không bằng túp lều cỏ nhỏ ấm áp khói bếp bay lên." },
  { id: 205, content: "Bão đêm qua quật đổ cây cổ thụ nghìn năm, nhưng bụi cỏ ven đường vẫn xanh rì, mềm mại sống dai hơn." },
  { id: 206, content: "Krog muốn hái quả ngọt trên ngọn cây cao vút? Học cách ngã vài lần đau mông ê ẩm trước đã nhé." },
  { id: 207, content: "Tranh cãi với con vẹt rừng chỉ tổ mỏi họng, nó chỉ nói lại những gì nó nghe chứ không có não suy nghĩ." },
  { id: 208, content: "Ăn quả vả rừng nhớ ơn người trồng cây xuống đất, ăn thịt hoẵng nhớ ơn người thợ mài rìu sắc bén." },
  { id: 209, content: "Túi da báo rách có thể dùng gân thú khâu lại, lòng tin vỡ rồi khâu lại vẫn hằn lên vết sẹo xù xì." },
  { id: 210, content: "Thấy người khác săn được voi đại ngàn krog chớ nản lòng, voi to khó khiêng, hoẵng nhỏ vừa miếng ăn." },
  { id: 211, content: "Đom đóm lập lòe không thắp sáng được hang to, nhưng làm đêm tối bớt phần đáng sợ, việc tốt nhỏ cũng vậy." },
  { id: 212, content: "Trời mưa to thì trú hang đá, trời nắng ấm thì phơi váy vỏ cây, thuận theo ông trời krog sống thọ vô biên." },
  { id: 213, content: "Cái bụng đói rã rời là người thầy tốt nhất, nó dạy krog biết giá trị trân quý của một hạt ngô rơi." },
  { id: 214, content: "Đừng đem con cá lên bờ dạy nó cách leo cây cổ thụ, đừng bắt krog thích vẽ tranh phải đi săn cọp giỏi." },
  { id: 215, content: "Krog ghen tị với bộ lông sặc sỡ của con công làm gì? Công đẹp nhưng thịt dai ngoanh ngoách chẳng béo bở." },
  { id: 216, content: "Đá nhọn đâm đau chân krog, nhưng nhờ có vết đau đó krog mới biết nhìn xuống đường khi bước đi." },
  { id: 217, content: "Ngồi một chỗ than vãn khóc lóc không làm củi tự khô đâu, nhấc mông lên và mang chúng ra phơi nắng đi." },
  { id: 218, content: "Lời nói dịu dàng như làn gió mùa xuân ấm áp, có thể làm tan chảy băng tuyết giá lạnh trong lòng krog khác." },
  { id: 219, content: "Khoe cây gậy to không làm krog mạnh mẽ hơn đâu, sức mạnh thực sự nằm ở cái đầu biết né bẫy thú rừng." },
  { id: 220, content: "Chê bai dòng suối đục ngầu hôm nay làm gì, ngày mai nắng hạn cháy da nước đục krog cũng thèm nhỏ dãi." },
  { id: 221, content: "Con ong chăm chỉ hút mật hoa thơm, không bận tâm con ruồi bay quanh đống phân, krog hãy sống như con ong." },
  { id: 222, content: "Cơn giận dữ giống như lửa cháy hừng hực trong tay, krog định ném vào người khác nhưng chính krog bị bỏng trước." },
  { id: 223, content: "Mất một cái rìu đá quý? Coi như cái rìu đó đi tìm chủ mới có duyên hơn, nghĩ thoáng ra cho nhẹ đầu." },
  { id: 224, content: "Người khôn ngoan biết rõ lúc nào nên hú lên gọi bầy cứu viện, lúc nào nên im lặng núp kỹ sau bụi rậm." },
  { id: 225, content: "Mùa đông lạnh giá thấu xương nhắc krog nhớ rằng đốm lửa nhỏ ngày thường đáng trân quý biết bao nhiêu." },
  { id: 226, content: "Đừng cố lội qua dòng sông hung dữ khi nước đang cuộn đỏ ngầu, đợi vài ngày nước sẽ tự trong trở lại thôi." },
  { id: 227, content: "Vẽ hình con hươu béo tốt lên vách hang không làm bụng krog no, krog phải cầm giáo bước ra ngoài rừng xanh." },
  { id: 228, content: "Krog cười người khác vì họ không giống krog? Cả khu rừng có trăm loại lá, loại nào cũng có nét hay riêng." },
  { id: 229, content: "Một cái ôm ấm áp từ krog nhà mình đáng giá hơn vạn lời khen sáo rỗng ngoài bờ suối vắng." },
  { id: 230, content: "Đi săn một mình thì đi nhanh, đi săn cùng bộ tộc thì đi xa, muốn bắt voi đại ngàn phải đi đông người." },
  { id: 231, content: "Quá khứ đã qua như tro tàn bếp lửa, tương lai chưa tới như mầm non dưới đất, hãy sống cho củ khoai hôm nay." },
  { id: 232, content: "Đừng đổ lỗi cho bóng đêm tối tăm mịt mùng, hãy tự trách mình chưa chuẩn bị sẵn một bó đuốc to từ chiều." },
  { id: 233, content: "Sông sâu nước chảy lặng lờ êm ả, krog nông nổi thiếu hiểu biết thì hay oang oang cái miệng suốt ngày." },
  { id: 234, content: "Nhìn thấy tổ ong mật trên cành cây cao? Đừng vội chọc gậy, hãy chuẩn bị khói củi để đuổi ong trước đã." },
  { id: 235, content: "Một lời nói ác ý lúc nóng giận cần đến mười rổ quả ngọt cũng không tài nào bù đắp nổi vết thương lòng." },
  { id: 236, content: "Krog mệt mỏi vì mải miết đuổi theo con bướm hoa? Đứng im một lát hoa nở rộ bướm tự khắc bay đến bên krog." },
  { id: 237, content: "Hãy biết bảo vệ đốm lửa nhỏ của mình trước gió lớn, đừng đi thổi tắt ngọn lửa của hang hàng xóm làm gì." },
  { id: 238, content: "Trái cây chín ép ăn chát ngắt đắng nghét, tình cảm vội vàng dễ rạn nứt tổn thương, hãy cứ thong thả sống." },
  { id: 239, content: "Krog có hai cái tai và một cái miệng, hãy học cách lắng nghe nhiều hơn gấp đôi số lời krog nói ra ngoài." },
  { id: 240, content: "Con khỉ chuyền cành hay ngã lộn cổ vì nó quá tự tin vào tài nghệ, krog đi dưới đất cứ cẩn thận từng bước." },
  { id: 241, content: "Đá cuội mịn màng nhờ dòng nước suối vỗ về nghìn năm, krog tốt lên nhờ vượt qua những va vấp cuộc đời." },
  { id: 242, content: "Đừng cầu mong khu rừng không có thú dữ nguy hiểm, hãy cầu mong cánh tay krog đủ khỏe để cầm chắc ngọn giáo." },
  { id: 243, content: "Nuôi một con chó nhỏ từ bé, nó trung thành hơn vạn lời thề non hẹn biển của những krog lạ hoắc ngoài kia." },
  { id: 244, content: "Thấy trời sập thì có krog cao hơn giơ tay đỡ, krog lùn cứ yên tâm ngồi nhai củ mài nướng cho ấm bụng." },
  { id: 245, content: "Biết ơn con suối cho nước uống mỗi ngày, biết ơn mặt trời cho hơi ấm, biết ơn mặt đất cho chỗ ngả lưng ngủ." },
  { id: 246, content: "Kẻ thích chỉ tay năm ngón ra lệnh thường là kẻ không biết cầm rìu đá chặt củi sao cho đúng cách." },
  { id: 247, content: "Học cách từ chối miếng thịt hoẵng đã ôi thiu bốc mùi, krog sẽ tránh được cái bụng đau quặn thắt đêm ngày." },
  { id: 248, content: "Một ngày không làm được việc gì có ích thì đêm nằm ngủ lưng thấy cộm, lòng thấy bồn chồn khó yên giấc." },
  { id: 249, content: "Đừng hứa cho người khác nửa con lợn rừng béo tốt khi mũi tên của krog còn chưa lắp vào dây cung nhé." },
  { id: 250, content: "Lông chim công lộng lẫy thật đấy, nhưng không giữ ấm được cho krog bằng tấm da gấu xù xì thô ráp." },
  { id: 251, content: "Khi bộ tộc xảy ra tranh cãi om sòm, krog thông minh chọn đi nhặt củi khô, vừa được việc vừa đỡ nhức đầu." },
  { id: 252, content: "Củ khoai đừng vứt bỏ khi bão về." },
  { id: 253, content: "Củ khoai đừng vứt bỏ giữa rừng sâu." },
  { id: 254, content: "Củ khoai đừng vứt bỏ vào mùa đông." },
  { id: 255, content: "Củ khoai đừng vứt bỏ sau cơn mưa." },
  { id: 256, content: "Củ khoai đừng vứt bỏ mỗi sớm mai." },
  { id: 257, content: "Củ khoai đừng vứt bỏ trong đêm tối." },
  { id: 258, content: "Củ khoai đừng vứt bỏ bên bờ suối." },
  { id: 259, content: "Củ khoai đừng vứt bỏ dưới gốc cây." },
  { id: 260, content: "Củ khoai đừng vứt bỏ khi đói lòng." },
  { id: 261, content: "Củ khoai đừng vứt bỏ suốt cuộc đời." },
  { id: 262, content: "Củ khoai hãy trân trọng khi bão về." },
  { id: 263, content: "Củ khoai hãy trân trọng giữa rừng sâu." },
  { id: 264, content: "Củ khoai hãy trân trọng vào mùa đông." },
  { id: 265, content: "Củ khoai hãy trân trọng sau cơn mưa." },
  { id: 266, content: "Củ khoai hãy trân trọng mỗi sớm mai." },
  { id: 267, content: "Củ khoai hãy trân trọng trong đêm tối." },
  { id: 268, content: "Củ khoai hãy trân trọng bên bờ suối." },
  { id: 269, content: "Củ khoai hãy trân trọng dưới gốc cây." },
  { id: 270, content: "Củ khoai hãy trân trọng khi đói lòng." },
  { id: 271, content: "Củ khoai hãy trân trọng suốt cuộc đời." },
  { id: 272, content: "Củ khoai chớ coi thường khi bão về." },
  { id: 273, content: "Củ khoai chớ coi thường giữa rừng sâu." },
  { id: 274, content: "Củ khoai chớ coi thường vào mùa đông." },
  { id: 275, content: "Củ khoai chớ coi thường sau cơn mưa." },
  { id: 276, content: "Củ khoai chớ coi thường mỗi sớm mai." },
  { id: 277, content: "Củ khoai chớ coi thường trong đêm tối." },
  { id: 278, content: "Củ khoai chớ coi thường bên bờ suối." },
  { id: 279, content: "Củ khoai chớ coi thường dưới gốc cây." },
  { id: 280, content: "Củ khoai chớ coi thường khi đói lòng." },
  { id: 281, content: "Củ khoai chớ coi thường suốt cuộc đời." },
  { id: 282, content: "Củ khoai cần được giữ gìn khi bão về." },
  { id: 283, content: "Củ khoai cần được giữ gìn giữa rừng sâu." },
  { id: 284, content: "Củ khoai cần được giữ gìn vào mùa đông." },
  { id: 285, content: "Củ khoai cần được giữ gìn sau cơn mưa." },
  { id: 286, content: "Củ khoai cần được giữ gìn mỗi sớm mai." },
  { id: 287, content: "Củ khoai cần được giữ gìn trong đêm tối." },
  { id: 288, content: "Củ khoai cần được giữ gìn bên bờ suối." },
  { id: 289, content: "Củ khoai cần được giữ gìn dưới gốc cây." },
  { id: 290, content: "Củ khoai cần được giữ gìn khi đói lòng." },
  { id: 291, content: "Củ khoai cần được giữ gìn suốt cuộc đời." },
  { id: 292, content: "Củ khoai giúp krog ấm lòng khi bão về." },
  { id: 293, content: "Củ khoai giúp krog ấm lòng giữa rừng sâu." },
  { id: 294, content: "Củ khoai giúp krog ấm lòng vào mùa đông." },
  { id: 295, content: "Củ khoai giúp krog ấm lòng sau cơn mưa." },
  { id: 296, content: "Củ khoai giúp krog ấm lòng mỗi sớm mai." },
  { id: 297, content: "Củ khoai giúp krog ấm lòng trong đêm tối." },
  { id: 298, content: "Củ khoai giúp krog ấm lòng bên bờ suối." },
  { id: 299, content: "Củ khoai giúp krog ấm lòng dưới gốc cây." },
  { id: 300, content: "Củ khoai giúp krog ấm lòng khi đói lòng." },
  { id: 301, content: "Củ khoai giúp krog ấm lòng suốt cuộc đời." },
  { id: 302, content: "Củ khoai nuôi sống krog khi bão về." },
  { id: 303, content: "Củ khoai nuôi sống krog giữa rừng sâu." },
  { id: 304, content: "Củ khoai nuôi sống krog vào mùa đông." },
  { id: 305, content: "Củ khoai nuôi sống krog sau cơn mưa." },
  { id: 306, content: "Củ khoai nuôi sống krog mỗi sớm mai." },
  { id: 307, content: "Củ khoai nuôi sống krog trong đêm tối." },
  { id: 308, content: "Củ khoai nuôi sống krog bên bờ suối." },
  { id: 309, content: "Củ khoai nuôi sống krog dưới gốc cây." },
  { id: 310, content: "Củ khoai nuôi sống krog khi đói lòng." },
  { id: 311, content: "Củ khoai nuôi sống krog suốt cuộc đời." },
  { id: 312, content: "Củ khoai dạy krog bài học khi bão về." },
  { id: 313, content: "Củ khoai dạy krog bài học giữa rừng sâu." },
  { id: 314, content: "Củ khoai dạy krog bài học vào mùa đông." },
  { id: 315, content: "Củ khoai dạy krog bài học sau cơn mưa." },
  { id: 316, content: "Củ khoai dạy krog bài học mỗi sớm mai." },
  { id: 317, content: "Củ khoai dạy krog bài học trong đêm tối." },
  { id: 318, content: "Củ khoai dạy krog bài học bên bờ suối." },
  { id: 319, content: "Củ khoai dạy krog bài học dưới gốc cây." },
  { id: 320, content: "Củ khoai dạy krog bài học khi đói lòng." },
  { id: 321, content: "Củ khoai dạy krog bài học suốt cuộc đời." },
  { id: 322, content: "Củ khoai làm đầu krog đau khi bão về." },
  { id: 323, content: "Củ khoai làm đầu krog đau giữa rừng sâu." },
  { id: 324, content: "Củ khoai làm đầu krog đau vào mùa đông." },
  { id: 325, content: "Củ khoai làm đầu krog đau sau cơn mưa." },
  { id: 326, content: "Củ khoai làm đầu krog đau mỗi sớm mai." },
  { id: 327, content: "Củ khoai làm đầu krog đau trong đêm tối." },
  { id: 328, content: "Củ khoai làm đầu krog đau bên bờ suối." },
  { id: 329, content: "Củ khoai làm đầu krog đau dưới gốc cây." },
  { id: 330, content: "Củ khoai làm đầu krog đau khi đói lòng." },
  { id: 331, content: "Củ khoai làm đầu krog đau suốt cuộc đời." },
  { id: 332, content: "Củ khoai mang lại niềm vui khi bão về." },
  { id: 333, content: "Củ khoai mang lại niềm vui giữa rừng sâu." },
  { id: 334, content: "Củ khoai mang lại niềm vui vào mùa đông." },
  { id: 335, content: "Củ khoai mang lại niềm vui sau cơn mưa." },
  { id: 336, content: "Củ khoai mang lại niềm vui mỗi sớm mai." },
  { id: 337, content: "Củ khoai mang lại niềm vui trong đêm tối." },
  { id: 338, content: "Củ khoai mang lại niềm vui bên bờ suối." },
  { id: 339, content: "Củ khoai mang lại niềm vui dưới gốc cây." },
  { id: 340, content: "Củ khoai mang lại niềm vui khi đói lòng." },
  { id: 341, content: "Củ khoai mang lại niềm vui suốt cuộc đời." },
  { id: 342, content: "Củ khoai xua tan bóng đêm khi bão về." },
  { id: 343, content: "Củ khoai xua tan bóng đêm giữa rừng sâu." },
  { id: 344, content: "Củ khoai xua tan bóng đêm vào mùa đông." },
  { id: 345, content: "Củ khoai xua tan bóng đêm sau cơn mưa." },
  { id: 346, content: "Củ khoai xua tan bóng đêm mỗi sớm mai." },
  { id: 347, content: "Củ khoai xua tan bóng đêm trong đêm tối." },
  { id: 348, content: "Củ khoai xua tan bóng đêm bên bờ suối." },
  { id: 349, content: "Củ khoai xua tan bóng đêm dưới gốc cây." },
  { id: 350, content: "Củ khoai xua tan bóng đêm khi đói lòng." },
  { id: 351, content: "Củ khoai xua tan bóng đêm suốt cuộc đời." },
  { id: 352, content: "Hòn đá cuội đừng vứt bỏ khi bão về." },
  { id: 353, content: "Hòn đá cuội đừng vứt bỏ giữa rừng sâu." },
  { id: 354, content: "Hòn đá cuội đừng vứt bỏ vào mùa đông." },
  { id: 355, content: "Hòn đá cuội đừng vứt bỏ sau cơn mưa." },
  { id: 356, content: "Hòn đá cuội đừng vứt bỏ mỗi sớm mai." },
  { id: 357, content: "Hòn đá cuội đừng vứt bỏ trong đêm tối." },
  { id: 358, content: "Hòn đá cuội đừng vứt bỏ bên bờ suối." },
  { id: 359, content: "Hòn đá cuội đừng vứt bỏ dưới gốc cây." },
  { id: 360, content: "Hòn đá cuội đừng vứt bỏ khi đói lòng." },
  { id: 361, content: "Hòn đá cuội đừng vứt bỏ suốt cuộc đời." },
  { id: 362, content: "Hòn đá cuội hãy trân trọng khi bão về." },
  { id: 363, content: "Hòn đá cuội hãy trân trọng giữa rừng sâu." },
  { id: 364, content: "Hòn đá cuội hãy trân trọng vào mùa đông." },
  { id: 365, content: "Hòn đá cuội hãy trân trọng sau cơn mưa." },
  { id: 366, content: "Hòn đá cuội hãy trân trọng mỗi sớm mai." },
  { id: 367, content: "Hòn đá cuội hãy trân trọng trong đêm tối." },
  { id: 368, content: "Hòn đá cuội hãy trân trọng bên bờ suối." },
  { id: 369, content: "Hòn đá cuội hãy trân trọng dưới gốc cây." },
  { id: 370, content: "Hòn đá cuội hãy trân trọng khi đói lòng." },
  { id: 371, content: "Hòn đá cuội hãy trân trọng suốt cuộc đời." },
  { id: 372, content: "Hòn đá cuội chớ coi thường khi bão về." },
  { id: 373, content: "Hòn đá cuội chớ coi thường giữa rừng sâu." },
  { id: 374, content: "Hòn đá cuội chớ coi thường vào mùa đông." },
  { id: 375, content: "Hòn đá cuội chớ coi thường sau cơn mưa." },
  { id: 376, content: "Hòn đá cuội chớ coi thường mỗi sớm mai." },
  { id: 377, content: "Hòn đá cuội chớ coi thường trong đêm tối." },
  { id: 378, content: "Hòn đá cuội chớ coi thường bên bờ suối." },
  { id: 379, content: "Hòn đá cuội chớ coi thường dưới gốc cây." },
  { id: 380, content: "Hòn đá cuội chớ coi thường khi đói lòng." },
  { id: 381, content: "Hòn đá cuội chớ coi thường suốt cuộc đời." },
  { id: 382, content: "Hòn đá cuội cần được giữ gìn khi bão về." },
  { id: 383, content: "Hòn đá cuội cần được giữ gìn giữa rừng sâu." },
  { id: 384, content: "Hòn đá cuội cần được giữ gìn vào mùa đông." },
  { id: 385, content: "Hòn đá cuội cần được giữ gìn sau cơn mưa." },
  { id: 386, content: "Hòn đá cuội cần được giữ gìn mỗi sớm mai." },
  { id: 387, content: "Hòn đá cuội cần được giữ gìn trong đêm tối." },
  { id: 388, content: "Hòn đá cuội cần được giữ gìn bên bờ suối." },
  { id: 389, content: "Hòn đá cuội cần được giữ gìn dưới gốc cây." },
  { id: 390, content: "Hòn đá cuội cần được giữ gìn khi đói lòng." },
  { id: 391, content: "Hòn đá cuội cần được giữ gìn suốt cuộc đời." },
  { id: 392, content: "Hòn đá cuội giúp krog ấm lòng khi bão về." },
  { id: 393, content: "Hòn đá cuội giúp krog ấm lòng giữa rừng sâu." },
  { id: 394, content: "Hòn đá cuội giúp krog ấm lòng vào mùa đông." },
  { id: 395, content: "Hòn đá cuội giúp krog ấm lòng sau cơn mưa." },
  { id: 396, content: "Hòn đá cuội giúp krog ấm lòng mỗi sớm mai." },
  { id: 397, content: "Hòn đá cuội giúp krog ấm lòng trong đêm tối." },
  { id: 398, content: "Hòn đá cuội giúp krog ấm lòng bên bờ suối." },
  { id: 399, content: "Hòn đá cuội giúp krog ấm lòng dưới gốc cây." },
  { id: 400, content: "Hòn đá cuội giúp krog ấm lòng khi đói lòng." },
  { id: 401, content: "Hòn đá cuội giúp krog ấm lòng suốt cuộc đời." },
  { id: 402, content: "Hòn đá cuội nuôi sống krog khi bão về." },
  { id: 403, content: "Hòn đá cuội nuôi sống krog giữa rừng sâu." },
  { id: 404, content: "Hòn đá cuội nuôi sống krog vào mùa đông." },
  { id: 405, content: "Hòn đá cuội nuôi sống krog sau cơn mưa." },
  { id: 406, content: "Hòn đá cuội nuôi sống krog mỗi sớm mai." },
  { id: 407, content: "Hòn đá cuội nuôi sống krog trong đêm tối." },
  { id: 408, content: "Hòn đá cuội nuôi sống krog bên bờ suối." },
  { id: 409, content: "Hòn đá cuội nuôi sống krog dưới gốc cây." },
  { id: 410, content: "Hòn đá cuội nuôi sống krog khi đói lòng." },
  { id: 411, content: "Hòn đá cuội nuôi sống krog suốt cuộc đời." },
  { id: 412, content: "Hòn đá cuội dạy krog bài học khi bão về." },
  { id: 413, content: "Hòn đá cuội dạy krog bài học giữa rừng sâu." },
  { id: 414, content: "Hòn đá cuội dạy krog bài học vào mùa đông." },
  { id: 415, content: "Hòn đá cuội dạy krog bài học sau cơn mưa." },
  { id: 416, content: "Hòn đá cuội dạy krog bài học mỗi sớm mai." },
  { id: 417, content: "Hòn đá cuội dạy krog bài học trong đêm tối." },
  { id: 418, content: "Hòn đá cuội dạy krog bài học bên bờ suối." },
  { id: 419, content: "Hòn đá cuội dạy krog bài học dưới gốc cây." },
  { id: 420, content: "Hòn đá cuội dạy krog bài học khi đói lòng." },
  { id: 421, content: "Hòn đá cuội dạy krog bài học suốt cuộc đời." },
  { id: 422, content: "Hòn đá cuội làm đầu krog đau khi bão về." },
  { id: 423, content: "Hòn đá cuội làm đầu krog đau giữa rừng sâu." },
  { id: 424, content: "Hòn đá cuội làm đầu krog đau vào mùa đông." },
  { id: 425, content: "Hòn đá cuội làm đầu krog đau sau cơn mưa." },
  { id: 426, content: "Hòn đá cuội làm đầu krog đau mỗi sớm mai." },
  { id: 427, content: "Hòn đá cuội làm đầu krog đau trong đêm tối." },
  { id: 428, content: "Hòn đá cuội làm đầu krog đau bên bờ suối." },
  { id: 429, content: "Hòn đá cuội làm đầu krog đau dưới gốc cây." },
  { id: 430, content: "Hòn đá cuội làm đầu krog đau khi đói lòng." },
  { id: 431, content: "Hòn đá cuội làm đầu krog đau suốt cuộc đời." },
  { id: 432, content: "Hòn đá cuội mang lại niềm vui khi bão về." },
  { id: 433, content: "Hòn đá cuội mang lại niềm vui giữa rừng sâu." },
  { id: 434, content: "Hòn đá cuội mang lại niềm vui vào mùa đông." },
  { id: 435, content: "Hòn đá cuội mang lại niềm vui sau cơn mưa." },
  { id: 436, content: "Hòn đá cuội mang lại niềm vui mỗi sớm mai." },
  { id: 437, content: "Hòn đá cuội mang lại niềm vui trong đêm tối." },
  { id: 438, content: "Hòn đá cuội mang lại niềm vui bên bờ suối." },
  { id: 439, content: "Hòn đá cuội mang lại niềm vui dưới gốc cây." },
  { id: 440, content: "Hòn đá cuội mang lại niềm vui khi đói lòng." },
  { id: 441, content: "Hòn đá cuội mang lại niềm vui suốt cuộc đời." },
  { id: 442, content: "Hòn đá cuội xua tan bóng đêm khi bão về." },
  { id: 443, content: "Hòn đá cuội xua tan bóng đêm giữa rừng sâu." },
  { id: 444, content: "Hòn đá cuội xua tan bóng đêm vào mùa đông." },
  { id: 445, content: "Hòn đá cuội xua tan bóng đêm sau cơn mưa." },
  { id: 446, content: "Hòn đá cuội xua tan bóng đêm mỗi sớm mai." },
  { id: 447, content: "Hòn đá cuội xua tan bóng đêm trong đêm tối." },
  { id: 448, content: "Hòn đá cuội xua tan bóng đêm bên bờ suối." },
  { id: 449, content: "Hòn đá cuội xua tan bóng đêm dưới gốc cây." },
  { id: 450, content: "Hòn đá cuội xua tan bóng đêm khi đói lòng." },
  { id: 451, content: "Hòn đá cuội xua tan bóng đêm suốt cuộc đời." },
  { id: 452, content: "Ngọn giáo đá đừng vứt bỏ khi bão về." },
  { id: 453, content: "Ngọn giáo đá đừng vứt bỏ giữa rừng sâu." },
  { id: 454, content: "Ngọn giáo đá đừng vứt bỏ vào mùa đông." },
  { id: 455, content: "Ngọn giáo đá đừng vứt bỏ sau cơn mưa." },
  { id: 456, content: "Ngọn giáo đá đừng vứt bỏ mỗi sớm mai." },
  { id: 457, content: "Ngọn giáo đá đừng vứt bỏ trong đêm tối." },
  { id: 458, content: "Ngọn giáo đá đừng vứt bỏ bên bờ suối." },
  { id: 459, content: "Ngọn giáo đá đừng vứt bỏ dưới gốc cây." },
  { id: 460, content: "Ngọn giáo đá đừng vứt bỏ khi đói lòng." },
  { id: 461, content: "Ngọn giáo đá đừng vứt bỏ suốt cuộc đời." },
  { id: 462, content: "Ngọn giáo đá hãy trân trọng khi bão về." },
  { id: 463, content: "Ngọn giáo đá hãy trân trọng giữa rừng sâu." },
  { id: 464, content: "Ngọn giáo đá hãy trân trọng vào mùa đông." },
  { id: 465, content: "Ngọn giáo đá hãy trân trọng sau cơn mưa." },
  { id: 466, content: "Ngọn giáo đá hãy trân trọng mỗi sớm mai." },
  { id: 467, content: "Ngọn giáo đá hãy trân trọng trong đêm tối." },
  { id: 468, content: "Ngọn giáo đá hãy trân trọng bên bờ suối." },
  { id: 469, content: "Ngọn giáo đá hãy trân trọng dưới gốc cây." },
  { id: 470, content: "Ngọn giáo đá hãy trân trọng khi đói lòng." },
  { id: 471, content: "Ngọn giáo đá hãy trân trọng suốt cuộc đời." },
  { id: 472, content: "Ngọn giáo đá chớ coi thường khi bão về." },
  { id: 473, content: "Ngọn giáo đá chớ coi thường giữa rừng sâu." },
  { id: 474, content: "Ngọn giáo đá chớ coi thường vào mùa đông." },
  { id: 475, content: "Ngọn giáo đá chớ coi thường sau cơn mưa." },
  { id: 476, content: "Ngọn giáo đá chớ coi thường mỗi sớm mai." },
  { id: 477, content: "Ngọn giáo đá chớ coi thường trong đêm tối." },
  { id: 478, content: "Ngọn giáo đá chớ coi thường bên bờ suối." },
  { id: 479, content: "Ngọn giáo đá chớ coi thường dưới gốc cây." },
  { id: 480, content: "Ngọn giáo đá chớ coi thường khi đói lòng." },
  { id: 481, content: "Ngọn giáo đá chớ coi thường suốt cuộc đời." },
  { id: 482, content: "Ngọn giáo đá cần được giữ gìn khi bão về." },
  { id: 483, content: "Ngọn giáo đá cần được giữ gìn giữa rừng sâu." },
  { id: 484, content: "Ngọn giáo đá cần được giữ gìn vào mùa đông." },
  { id: 485, content: "Ngọn giáo đá cần được giữ gìn sau cơn mưa." },
  { id: 486, content: "Ngọn giáo đá cần được giữ gìn mỗi sớm mai." },
  { id: 487, content: "Ngọn giáo đá cần được giữ gìn trong đêm tối." },
  { id: 488, content: "Ngọn giáo đá cần được giữ gìn bên bờ suối." },
  { id: 489, content: "Ngọn giáo đá cần được giữ gìn dưới gốc cây." },
  { id: 490, content: "Ngọn giáo đá cần được giữ gìn khi đói lòng." },
  { id: 491, content: "Ngọn giáo đá cần được giữ gìn suốt cuộc đời." },
  { id: 492, content: "Ngọn giáo đá giúp krog ấm lòng khi bão về." },
  { id: 493, content: "Ngọn giáo đá giúp krog ấm lòng giữa rừng sâu." },
  { id: 494, content: "Ngọn giáo đá giúp krog ấm lòng vào mùa đông." },
  { id: 495, content: "Ngọn giáo đá giúp krog ấm lòng sau cơn mưa." },
  { id: 496, content: "Ngọn giáo đá giúp krog ấm lòng mỗi sớm mai." },
  { id: 497, content: "Ngọn giáo đá giúp krog ấm lòng trong đêm tối." },
  { id: 498, content: "Ngọn giáo đá giúp krog ấm lòng bên bờ suối." },
  { id: 499, content: "Ngọn giáo đá giúp krog ấm lòng dưới gốc cây." },
  { id: 500, content: "Ngọn giáo đá giúp krog ấm lòng khi đói lòng." },
  { id: 501, content: "Ngọn giáo đá giúp krog ấm lòng suốt cuộc đời." },
  { id: 502, content: "Ngọn giáo đá nuôi sống krog khi bão về." },
  { id: 503, content: "Ngọn giáo đá nuôi sống krog giữa rừng sâu." },
  { id: 504, content: "Ngọn giáo đá nuôi sống krog vào mùa đông." },
  { id: 505, content: "Ngọn giáo đá nuôi sống krog sau cơn mưa." },
  { id: 506, content: "Ngọn giáo đá nuôi sống krog mỗi sớm mai." },
  { id: 507, content: "Ngọn giáo đá nuôi sống krog trong đêm tối." },
  { id: 508, content: "Ngọn giáo đá nuôi sống krog bên bờ suối." },
  { id: 509, content: "Ngọn giáo đá nuôi sống krog dưới gốc cây." },
  { id: 510, content: "Ngọn giáo đá nuôi sống krog khi đói lòng." },
  { id: 511, content: "Ngọn giáo đá nuôi sống krog suốt cuộc đời." },
  { id: 512, content: "Ngọn giáo đá dạy krog bài học khi bão về." },
  { id: 513, content: "Ngọn giáo đá dạy krog bài học giữa rừng sâu." },
  { id: 514, content: "Ngọn giáo đá dạy krog bài học vào mùa đông." },
  { id: 515, content: "Ngọn giáo đá dạy krog bài học sau cơn mưa." },
  { id: 516, content: "Ngọn giáo đá dạy krog bài học mỗi sớm mai." },
  { id: 517, content: "Ngọn giáo đá dạy krog bài học trong đêm tối." },
  { id: 518, content: "Ngọn giáo đá dạy krog bài học bên bờ suối." },
  { id: 519, content: "Ngọn giáo đá dạy krog bài học dưới gốc cây." },
  { id: 520, content: "Ngọn giáo đá dạy krog bài học khi đói lòng." },
  { id: 521, content: "Ngọn giáo đá dạy krog bài học suốt cuộc đời." },
  { id: 522, content: "Ngọn giáo đá làm đầu krog đau khi bão về." },
  { id: 523, content: "Ngọn giáo đá làm đầu krog đau giữa rừng sâu." },
  { id: 524, content: "Ngọn giáo đá làm đầu krog đau vào mùa đông." },
  { id: 525, content: "Ngọn giáo đá làm đầu krog đau sau cơn mưa." },
  { id: 526, content: "Ngọn giáo đá làm đầu krog đau mỗi sớm mai." },
  { id: 527, content: "Ngọn giáo đá làm đầu krog đau trong đêm tối." },
  { id: 528, content: "Ngọn giáo đá làm đầu krog đau bên bờ suối." },
  { id: 529, content: "Ngọn giáo đá làm đầu krog đau dưới gốc cây." },
  { id: 530, content: "Ngọn giáo đá làm đầu krog đau khi đói lòng." },
  { id: 531, content: "Ngọn giáo đá làm đầu krog đau suốt cuộc đời." },
  { id: 532, content: "Ngọn giáo đá mang lại niềm vui khi bão về." },
  { id: 533, content: "Ngọn giáo đá mang lại niềm vui giữa rừng sâu." },
  { id: 534, content: "Ngọn giáo đá mang lại niềm vui vào mùa đông." },
  { id: 535, content: "Ngọn giáo đá mang lại niềm vui sau cơn mưa." },
  { id: 536, content: "Ngọn giáo đá mang lại niềm vui mỗi sớm mai." },
  { id: 537, content: "Ngọn giáo đá mang lại niềm vui trong đêm tối." },
  { id: 538, content: "Ngọn giáo đá mang lại niềm vui bên bờ suối." },
  { id: 539, content: "Ngọn giáo đá mang lại niềm vui dưới gốc cây." },
  { id: 540, content: "Ngọn giáo đá mang lại niềm vui khi đói lòng." },
  { id: 541, content: "Ngọn giáo đá mang lại niềm vui suốt cuộc đời." },
  { id: 542, content: "Ngọn giáo đá xua tan bóng đêm khi bão về." },
  { id: 543, content: "Ngọn giáo đá xua tan bóng đêm giữa rừng sâu." },
  { id: 544, content: "Ngọn giáo đá xua tan bóng đêm vào mùa đông." },
  { id: 545, content: "Ngọn giáo đá xua tan bóng đêm sau cơn mưa." },
  { id: 546, content: "Ngọn giáo đá xua tan bóng đêm mỗi sớm mai." },
  { id: 547, content: "Ngọn giáo đá xua tan bóng đêm trong đêm tối." },
  { id: 548, content: "Ngọn giáo đá xua tan bóng đêm bên bờ suối." },
  { id: 549, content: "Ngọn giáo đá xua tan bóng đêm dưới gốc cây." },
  { id: 550, content: "Ngọn giáo đá xua tan bóng đêm khi đói lòng." },
  { id: 551, content: "Ngọn giáo đá xua tan bóng đêm suốt cuộc đời." },
  { id: 552, content: "Bếp lửa hồng đừng vứt bỏ khi bão về." },
  { id: 553, content: "Bếp lửa hồng đừng vứt bỏ giữa rừng sâu." },
  { id: 554, content: "Bếp lửa hồng đừng vứt bỏ vào mùa đông." },
  { id: 555, content: "Bếp lửa hồng đừng vứt bỏ sau cơn mưa." },
  { id: 556, content: "Bếp lửa hồng đừng vứt bỏ mỗi sớm mai." },
  { id: 557, content: "Bếp lửa hồng đừng vứt bỏ trong đêm tối." },
  { id: 558, content: "Bếp lửa hồng đừng vứt bỏ bên bờ suối." },
  { id: 559, content: "Bếp lửa hồng đừng vứt bỏ dưới gốc cây." },
  { id: 560, content: "Bếp lửa hồng đừng vứt bỏ khi đói lòng." },
  { id: 561, content: "Bếp lửa hồng đừng vứt bỏ suốt cuộc đời." },
  { id: 562, content: "Bếp lửa hồng hãy trân trọng khi bão về." },
  { id: 563, content: "Bếp lửa hồng hãy trân trọng giữa rừng sâu." },
  { id: 564, content: "Bếp lửa hồng hãy trân trọng vào mùa đông." },
  { id: 565, content: "Bếp lửa hồng hãy trân trọng sau cơn mưa." },
  { id: 566, content: "Bếp lửa hồng hãy trân trọng mỗi sớm mai." },
  { id: 567, content: "Bếp lửa hồng hãy trân trọng trong đêm tối." },
  { id: 568, content: "Bếp lửa hồng hãy trân trọng bên bờ suối." },
  { id: 569, content: "Bếp lửa hồng hãy trân trọng dưới gốc cây." },
  { id: 570, content: "Bếp lửa hồng hãy trân trọng khi đói lòng." },
  { id: 571, content: "Bếp lửa hồng hãy trân trọng suốt cuộc đời." },
  { id: 572, content: "Bếp lửa hồng chớ coi thường khi bão về." },
  { id: 573, content: "Bếp lửa hồng chớ coi thường giữa rừng sâu." },
  { id: 574, content: "Bếp lửa hồng chớ coi thường vào mùa đông." },
  { id: 575, content: "Bếp lửa hồng chớ coi thường sau cơn mưa." },
  { id: 576, content: "Bếp lửa hồng chớ coi thường mỗi sớm mai." },
  { id: 577, content: "Bếp lửa hồng chớ coi thường trong đêm tối." },
  { id: 578, content: "Bếp lửa hồng chớ coi thường bên bờ suối." },
  { id: 579, content: "Bếp lửa hồng chớ coi thường dưới gốc cây." },
  { id: 580, content: "Bếp lửa hồng chớ coi thường khi đói lòng." },
  { id: 581, content: "Bếp lửa hồng chớ coi thường suốt cuộc đời." },
  { id: 582, content: "Bếp lửa hồng cần được giữ gìn khi bão về." },
  { id: 583, content: "Bếp lửa hồng cần được giữ gìn giữa rừng sâu." },
  { id: 584, content: "Bếp lửa hồng cần được giữ gìn vào mùa đông." },
  { id: 585, content: "Bếp lửa hồng cần được giữ gìn sau cơn mưa." },
  { id: 586, content: "Bếp lửa hồng cần được giữ gìn mỗi sớm mai." },
  { id: 587, content: "Bếp lửa hồng cần được giữ gìn trong đêm tối." },
  { id: 588, content: "Bếp lửa hồng cần được giữ gìn bên bờ suối." },
  { id: 589, content: "Bếp lửa hồng cần được giữ gìn dưới gốc cây." },
  { id: 590, content: "Bếp lửa hồng cần được giữ gìn khi đói lòng." },
  { id: 591, content: "Bếp lửa hồng cần được giữ gìn suốt cuộc đời." },
  { id: 592, content: "Bếp lửa hồng giúp krog ấm lòng khi bão về." },
  { id: 593, content: "Bếp lửa hồng giúp krog ấm lòng giữa rừng sâu." },
  { id: 594, content: "Bếp lửa hồng giúp krog ấm lòng vào mùa đông." },
  { id: 595, content: "Bếp lửa hồng giúp krog ấm lòng sau cơn mưa." },
  { id: 596, content: "Bếp lửa hồng giúp krog ấm lòng mỗi sớm mai." },
  { id: 597, content: "Bếp lửa hồng giúp krog ấm lòng trong đêm tối." },
  { id: 598, content: "Bếp lửa hồng giúp krog ấm lòng bên bờ suối." },
  { id: 599, content: "Bếp lửa hồng giúp krog ấm lòng dưới gốc cây." },
  { id: 600, content: "Bếp lửa hồng giúp krog ấm lòng khi đói lòng." },
  { id: 601, content: "Bếp lửa hồng giúp krog ấm lòng suốt cuộc đời." },
  { id: 602, content: "Bếp lửa hồng nuôi sống krog khi bão về." },
  { id: 603, content: "Bếp lửa hồng nuôi sống krog giữa rừng sâu." },
  { id: 604, content: "Bếp lửa hồng nuôi sống krog vào mùa đông." },
  { id: 605, content: "Bếp lửa hồng nuôi sống krog sau cơn mưa." },
  { id: 606, content: "Bếp lửa hồng nuôi sống krog mỗi sớm mai." },
  { id: 607, content: "Bếp lửa hồng nuôi sống krog trong đêm tối." },
  { id: 608, content: "Bếp lửa hồng nuôi sống krog bên bờ suối." },
  { id: 609, content: "Bếp lửa hồng nuôi sống krog dưới gốc cây." },
  { id: 610, content: "Bếp lửa hồng nuôi sống krog khi đói lòng." },
  { id: 611, content: "Bếp lửa hồng nuôi sống krog suốt cuộc đời." },
  { id: 612, content: "Bếp lửa hồng dạy krog bài học khi bão về." },
  { id: 613, content: "Bếp lửa hồng dạy krog bài học giữa rừng sâu." },
  { id: 614, content: "Bếp lửa hồng dạy krog bài học vào mùa đông." },
  { id: 615, content: "Bếp lửa hồng dạy krog bài học sau cơn mưa." },
  { id: 616, content: "Bếp lửa hồng dạy krog bài học mỗi sớm mai." },
  { id: 617, content: "Bếp lửa hồng dạy krog bài học trong đêm tối." },
  { id: 618, content: "Bếp lửa hồng dạy krog bài học bên bờ suối." },
  { id: 619, content: "Bếp lửa hồng dạy krog bài học dưới gốc cây." },
  { id: 620, content: "Bếp lửa hồng dạy krog bài học khi đói lòng." },
  { id: 621, content: "Bếp lửa hồng dạy krog bài học suốt cuộc đời." },
  { id: 622, content: "Bếp lửa hồng làm đầu krog đau khi bão về." },
  { id: 623, content: "Bếp lửa hồng làm đầu krog đau giữa rừng sâu." },
  { id: 624, content: "Bếp lửa hồng làm đầu krog đau vào mùa đông." },
  { id: 625, content: "Bếp lửa hồng làm đầu krog đau sau cơn mưa." },
  { id: 626, content: "Bếp lửa hồng làm đầu krog đau mỗi sớm mai." },
  { id: 627, content: "Bếp lửa hồng làm đầu krog đau trong đêm tối." },
  { id: 628, content: "Bếp lửa hồng làm đầu krog đau bên bờ suối." },
  { id: 629, content: "Bếp lửa hồng làm đầu krog đau dưới gốc cây." },
  { id: 630, content: "Bếp lửa hồng làm đầu krog đau khi đói lòng." },
  { id: 631, content: "Bếp lửa hồng làm đầu krog đau suốt cuộc đời." },
  { id: 632, content: "Bếp lửa hồng mang lại niềm vui khi bão về." },
  { id: 633, content: "Bếp lửa hồng mang lại niềm vui giữa rừng sâu." },
  { id: 634, content: "Bếp lửa hồng mang lại niềm vui vào mùa đông." },
  { id: 635, content: "Bếp lửa hồng mang lại niềm vui sau cơn mưa." },
  { id: 636, content: "Bếp lửa hồng mang lại niềm vui mỗi sớm mai." },
  { id: 637, content: "Bếp lửa hồng mang lại niềm vui trong đêm tối." },
  { id: 638, content: "Bếp lửa hồng mang lại niềm vui bên bờ suối." },
  { id: 639, content: "Bếp lửa hồng mang lại niềm vui dưới gốc cây." },
  { id: 640, content: "Bếp lửa hồng mang lại niềm vui khi đói lòng." },
  { id: 641, content: "Bếp lửa hồng mang lại niềm vui suốt cuộc đời." },
  { id: 642, content: "Bếp lửa hồng xua tan bóng đêm khi bão về." },
  { id: 643, content: "Bếp lửa hồng xua tan bóng đêm giữa rừng sâu." },
  { id: 644, content: "Bếp lửa hồng xua tan bóng đêm vào mùa đông." },
  { id: 645, content: "Bếp lửa hồng xua tan bóng đêm sau cơn mưa." },
  { id: 646, content: "Bếp lửa hồng xua tan bóng đêm mỗi sớm mai." },
  { id: 647, content: "Bếp lửa hồng xua tan bóng đêm trong đêm tối." },
  { id: 648, content: "Bếp lửa hồng xua tan bóng đêm bên bờ suối." },
  { id: 649, content: "Bếp lửa hồng xua tan bóng đêm dưới gốc cây." },
  { id: 650, content: "Bếp lửa hồng xua tan bóng đêm khi đói lòng." },
  { id: 651, content: "Bếp lửa hồng xua tan bóng đêm suốt cuộc đời." },
  { id: 652, content: "Hang đá nhỏ đừng vứt bỏ khi bão về." },
  { id: 653, content: "Hang đá nhỏ đừng vứt bỏ giữa rừng sâu." },
  { id: 654, content: "Hang đá nhỏ đừng vứt bỏ vào mùa đông." },
  { id: 655, content: "Hang đá nhỏ đừng vứt bỏ sau cơn mưa." },
  { id: 656, content: "Hang đá nhỏ đừng vứt bỏ mỗi sớm mai." },
  { id: 657, content: "Hang đá nhỏ đừng vứt bỏ trong đêm tối." },
  { id: 658, content: "Hang đá nhỏ đừng vứt bỏ bên bờ suối." },
  { id: 659, content: "Hang đá nhỏ đừng vứt bỏ dưới gốc cây." },
  { id: 660, content: "Hang đá nhỏ đừng vứt bỏ khi đói lòng." },
  { id: 661, content: "Hang đá nhỏ đừng vứt bỏ suốt cuộc đời." },
  { id: 662, content: "Hang đá nhỏ hãy trân trọng khi bão về." },
  { id: 663, content: "Hang đá nhỏ hãy trân trọng giữa rừng sâu." },
  { id: 664, content: "Hang đá nhỏ hãy trân trọng vào mùa đông." },
  { id: 665, content: "Hang đá nhỏ hãy trân trọng sau cơn mưa." },
  { id: 666, content: "Hang đá nhỏ hãy trân trọng mỗi sớm mai." },
  { id: 667, content: "Hang đá nhỏ hãy trân trọng trong đêm tối." },
  { id: 668, content: "Hang đá nhỏ hãy trân trọng bên bờ suối." },
  { id: 669, content: "Hang đá nhỏ hãy trân trọng dưới gốc cây." },
  { id: 670, content: "Hang đá nhỏ hãy trân trọng khi đói lòng." },
  { id: 671, content: "Hang đá nhỏ hãy trân trọng suốt cuộc đời." },
  { id: 672, content: "Hang đá nhỏ chớ coi thường khi bão về." },
  { id: 673, content: "Hang đá nhỏ chớ coi thường giữa rừng sâu." },
  { id: 674, content: "Hang đá nhỏ chớ coi thường vào mùa đông." },
  { id: 675, content: "Hang đá nhỏ chớ coi thường sau cơn mưa." },
  { id: 676, content: "Hang đá nhỏ chớ coi thường mỗi sớm mai." },
  { id: 677, content: "Hang đá nhỏ chớ coi thường trong đêm tối." },
  { id: 678, content: "Hang đá nhỏ chớ coi thường bên bờ suối." },
  { id: 679, content: "Hang đá nhỏ chớ coi thường dưới gốc cây." },
  { id: 680, content: "Hang đá nhỏ chớ coi thường khi đói lòng." },
  { id: 681, content: "Hang đá nhỏ chớ coi thường suốt cuộc đời." },
  { id: 682, content: "Hang đá nhỏ cần được giữ gìn khi bão về." },
  { id: 683, content: "Hang đá nhỏ cần được giữ gìn giữa rừng sâu." },
  { id: 684, content: "Hang đá nhỏ cần được giữ gìn vào mùa đông." },
  { id: 685, content: "Hang đá nhỏ cần được giữ gìn sau cơn mưa." },
  { id: 686, content: "Hang đá nhỏ cần được giữ gìn mỗi sớm mai." },
  { id: 687, content: "Hang đá nhỏ cần được giữ gìn trong đêm tối." },
  { id: 688, content: "Hang đá nhỏ cần được giữ gìn bên bờ suối." },
  { id: 689, content: "Hang đá nhỏ cần được giữ gìn dưới gốc cây." },
  { id: 690, content: "Hang đá nhỏ cần được giữ gìn khi đói lòng." },
  { id: 691, content: "Hang đá nhỏ cần được giữ gìn suốt cuộc đời." },
  { id: 692, content: "Hang đá nhỏ giúp krog ấm lòng khi bão về." },
  { id: 693, content: "Hang đá nhỏ giúp krog ấm lòng giữa rừng sâu." },
  { id: 694, content: "Hang đá nhỏ giúp krog ấm lòng vào mùa đông." },
  { id: 695, content: "Hang đá nhỏ giúp krog ấm lòng sau cơn mưa." },
  { id: 696, content: "Hang đá nhỏ giúp krog ấm lòng mỗi sớm mai." },
  { id: 697, content: "Hang đá nhỏ giúp krog ấm lòng trong đêm tối." },
  { id: 698, content: "Hang đá nhỏ giúp krog ấm lòng bên bờ suối." },
  { id: 699, content: "Hang đá nhỏ giúp krog ấm lòng dưới gốc cây." },
  { id: 700, content: "Hang đá nhỏ giúp krog ấm lòng khi đói lòng." },
  { id: 701, content: "Hang đá nhỏ giúp krog ấm lòng suốt cuộc đời." },
  { id: 702, content: "Hang đá nhỏ nuôi sống krog khi bão về." },
  { id: 703, content: "Hang đá nhỏ nuôi sống krog giữa rừng sâu." },
  { id: 704, content: "Hang đá nhỏ nuôi sống krog vào mùa đông." },
  { id: 705, content: "Hang đá nhỏ nuôi sống krog sau cơn mưa." },
  { id: 706, content: "Hang đá nhỏ nuôi sống krog mỗi sớm mai." },
  { id: 707, content: "Hang đá nhỏ nuôi sống krog trong đêm tối." },
  { id: 708, content: "Hang đá nhỏ nuôi sống krog bên bờ suối." },
  { id: 709, content: "Hang đá nhỏ nuôi sống krog dưới gốc cây." },
  { id: 710, content: "Hang đá nhỏ nuôi sống krog khi đói lòng." },
  { id: 711, content: "Hang đá nhỏ nuôi sống krog suốt cuộc đời." },
  { id: 712, content: "Hang đá nhỏ dạy krog bài học khi bão về." },
  { id: 713, content: "Hang đá nhỏ dạy krog bài học giữa rừng sâu." },
  { id: 714, content: "Hang đá nhỏ dạy krog bài học vào mùa đông." },
  { id: 715, content: "Hang đá nhỏ dạy krog bài học sau cơn mưa." },
  { id: 716, content: "Hang đá nhỏ dạy krog bài học mỗi sớm mai." },
  { id: 717, content: "Hang đá nhỏ dạy krog bài học trong đêm tối." },
  { id: 718, content: "Hang đá nhỏ dạy krog bài học bên bờ suối." },
  { id: 719, content: "Hang đá nhỏ dạy krog bài học dưới gốc cây." },
  { id: 720, content: "Hang đá nhỏ dạy krog bài học khi đói lòng." },
  { id: 721, content: "Hang đá nhỏ dạy krog bài học suốt cuộc đời." },
  { id: 722, content: "Hang đá nhỏ làm đầu krog đau khi bão về." },
  { id: 723, content: "Hang đá nhỏ làm đầu krog đau giữa rừng sâu." },
  { id: 724, content: "Hang đá nhỏ làm đầu krog đau vào mùa đông." },
  { id: 725, content: "Hang đá nhỏ làm đầu krog đau sau cơn mưa." },
  { id: 726, content: "Hang đá nhỏ làm đầu krog đau mỗi sớm mai." },
  { id: 727, content: "Hang đá nhỏ làm đầu krog đau trong đêm tối." },
  { id: 728, content: "Hang đá nhỏ làm đầu krog đau bên bờ suối." },
  { id: 729, content: "Hang đá nhỏ làm đầu krog đau dưới gốc cây." },
  { id: 730, content: "Hang đá nhỏ làm đầu krog đau khi đói lòng." },
  { id: 731, content: "Hang đá nhỏ làm đầu krog đau suốt cuộc đời." },
  { id: 732, content: "Hang đá nhỏ mang lại niềm vui khi bão về." },
  { id: 733, content: "Hang đá nhỏ mang lại niềm vui giữa rừng sâu." },
  { id: 734, content: "Hang đá nhỏ mang lại niềm vui vào mùa đông." },
  { id: 735, content: "Hang đá nhỏ mang lại niềm vui sau cơn mưa." },
  { id: 736, content: "Hang đá nhỏ mang lại niềm vui mỗi sớm mai." },
  { id: 737, content: "Hang đá nhỏ mang lại niềm vui trong đêm tối." },
  { id: 738, content: "Hang đá nhỏ mang lại niềm vui bên bờ suối." },
  { id: 739, content: "Hang đá nhỏ mang lại niềm vui dưới gốc cây." },
  { id: 740, content: "Hang đá nhỏ mang lại niềm vui khi đói lòng." },
  { id: 741, content: "Hang đá nhỏ mang lại niềm vui suốt cuộc đời." },
  { id: 742, content: "Hang đá nhỏ xua tan bóng đêm khi bão về." },
  { id: 743, content: "Hang đá nhỏ xua tan bóng đêm giữa rừng sâu." },
  { id: 744, content: "Hang đá nhỏ xua tan bóng đêm vào mùa đông." },
  { id: 745, content: "Hang đá nhỏ xua tan bóng đêm sau cơn mưa." },
  { id: 746, content: "Hang đá nhỏ xua tan bóng đêm mỗi sớm mai." },
  { id: 747, content: "Hang đá nhỏ xua tan bóng đêm trong đêm tối." },
  { id: 748, content: "Hang đá nhỏ xua tan bóng đêm bên bờ suối." },
  { id: 749, content: "Hang đá nhỏ xua tan bóng đêm dưới gốc cây." },
  { id: 750, content: "Hang đá nhỏ xua tan bóng đêm khi đói lòng." },
  { id: 751, content: "Hang đá nhỏ xua tan bóng đêm suốt cuộc đời." },
  { id: 752, content: "Tộc trưởng đừng vứt bỏ khi bão về." },
  { id: 753, content: "Tộc trưởng đừng vứt bỏ giữa rừng sâu." },
  { id: 754, content: "Tộc trưởng đừng vứt bỏ vào mùa đông." },
  { id: 755, content: "Tộc trưởng đừng vứt bỏ sau cơn mưa." },
  { id: 756, content: "Tộc trưởng đừng vứt bỏ mỗi sớm mai." },
  { id: 757, content: "Tộc trưởng đừng vứt bỏ trong đêm tối." },
  { id: 758, content: "Tộc trưởng đừng vứt bỏ bên bờ suối." },
  { id: 759, content: "Tộc trưởng đừng vứt bỏ dưới gốc cây." },
  { id: 760, content: "Tộc trưởng đừng vứt bỏ khi đói lòng." },
  { id: 761, content: "Tộc trưởng đừng vứt bỏ suốt cuộc đời." },
  { id: 762, content: "Tộc trưởng hãy trân trọng khi bão về." },
  { id: 763, content: "Tộc trưởng hãy trân trọng giữa rừng sâu." },
  { id: 764, content: "Tộc trưởng hãy trân trọng vào mùa đông." },
  { id: 765, content: "Tộc trưởng hãy trân trọng sau cơn mưa." },
  { id: 766, content: "Tộc trưởng hãy trân trọng mỗi sớm mai." },
  { id: 767, content: "Tộc trưởng hãy trân trọng trong đêm tối." },
  { id: 768, content: "Tộc trưởng hãy trân trọng bên bờ suối." },
  { id: 769, content: "Tộc trưởng hãy trân trọng dưới gốc cây." },
  { id: 770, content: "Tộc trưởng hãy trân trọng khi đói lòng." },
  { id: 771, content: "Tộc trưởng hãy trân trọng suốt cuộc đời." },
  { id: 772, content: "Tộc trưởng chớ coi thường khi bão về." },
  { id: 773, content: "Tộc trưởng chớ coi thường giữa rừng sâu." },
  { id: 774, content: "Tộc trưởng chớ coi thường vào mùa đông." },
  { id: 775, content: "Tộc trưởng chớ coi thường sau cơn mưa." },
  { id: 776, content: "Tộc trưởng chớ coi thường mỗi sớm mai." },
  { id: 777, content: "Tộc trưởng chớ coi thường trong đêm tối." },
  { id: 778, content: "Tộc trưởng chớ coi thường bên bờ suối." },
  { id: 779, content: "Tộc trưởng chớ coi thường dưới gốc cây." },
  { id: 780, content: "Tộc trưởng chớ coi thường khi đói lòng." },
  { id: 781, content: "Tộc trưởng chớ coi thường suốt cuộc đời." },
  { id: 782, content: "Tộc trưởng cần được giữ gìn khi bão về." },
  { id: 783, content: "Tộc trưởng cần được giữ gìn giữa rừng sâu." },
  { id: 784, content: "Tộc trưởng cần được giữ gìn vào mùa đông." },
  { id: 785, content: "Tộc trưởng cần được giữ gìn sau cơn mưa." },
  { id: 786, content: "Tộc trưởng cần được giữ gìn mỗi sớm mai." },
  { id: 787, content: "Tộc trưởng cần được giữ gìn trong đêm tối." },
  { id: 788, content: "Tộc trưởng cần được giữ gìn bên bờ suối." },
  { id: 789, content: "Tộc trưởng cần được giữ gìn dưới gốc cây." },
  { id: 790, content: "Tộc trưởng cần được giữ gìn khi đói lòng." },
  { id: 791, content: "Tộc trưởng cần được giữ gìn suốt cuộc đời." },
  { id: 792, content: "Tộc trưởng giúp krog ấm lòng khi bão về." },
  { id: 793, content: "Tộc trưởng giúp krog ấm lòng giữa rừng sâu." },
  { id: 794, content: "Tộc trưởng giúp krog ấm lòng vào mùa đông." },
  { id: 795, content: "Tộc trưởng giúp krog ấm lòng sau cơn mưa." },
  { id: 796, content: "Tộc trưởng giúp krog ấm lòng mỗi sớm mai." },
  { id: 797, content: "Tộc trưởng giúp krog ấm lòng trong đêm tối." },
  { id: 798, content: "Tộc trưởng giúp krog ấm lòng bên bờ suối." },
  { id: 799, content: "Tộc trưởng giúp krog ấm lòng dưới gốc cây." },
  { id: 800, content: "Tộc trưởng giúp krog ấm lòng khi đói lòng." },
  { id: 801, content: "Tộc trưởng giúp krog ấm lòng suốt cuộc đời." },
  { id: 802, content: "Tộc trưởng nuôi sống krog khi bão về." },
  { id: 803, content: "Tộc trưởng nuôi sống krog giữa rừng sâu." },
  { id: 804, content: "Tộc trưởng nuôi sống krog vào mùa đông." },
  { id: 805, content: "Tộc trưởng nuôi sống krog sau cơn mưa." },
  { id: 806, content: "Tộc trưởng nuôi sống krog mỗi sớm mai." },
  { id: 807, content: "Tộc trưởng nuôi sống krog trong đêm tối." },
  { id: 808, content: "Tộc trưởng nuôi sống krog bên bờ suối." },
  { id: 809, content: "Tộc trưởng nuôi sống krog dưới gốc cây." },
  { id: 810, content: "Tộc trưởng nuôi sống krog khi đói lòng." },
  { id: 811, content: "Tộc trưởng nuôi sống krog suốt cuộc đời." },
  { id: 812, content: "Tộc trưởng dạy krog bài học khi bão về." },
  { id: 813, content: "Tộc trưởng dạy krog bài học giữa rừng sâu." },
  { id: 814, content: "Tộc trưởng dạy krog bài học vào mùa đông." },
  { id: 815, content: "Tộc trưởng dạy krog bài học sau cơn mưa." },
  { id: 816, content: "Tộc trưởng dạy krog bài học mỗi sớm mai." },
  { id: 817, content: "Tộc trưởng dạy krog bài học trong đêm tối." },
  { id: 818, content: "Tộc trưởng dạy krog bài học bên bờ suối." },
  { id: 819, content: "Tộc trưởng dạy krog bài học dưới gốc cây." },
  { id: 820, content: "Tộc trưởng dạy krog bài học khi đói lòng." },
  { id: 821, content: "Tộc trưởng dạy krog bài học suốt cuộc đời." },
  { id: 822, content: "Tộc trưởng làm đầu krog đau khi bão về." },
  { id: 823, content: "Tộc trưởng làm đầu krog đau giữa rừng sâu." },
  { id: 824, content: "Tộc trưởng làm đầu krog đau vào mùa đông." },
  { id: 825, content: "Tộc trưởng làm đầu krog đau sau cơn mưa." },
  { id: 826, content: "Tộc trưởng làm đầu krog đau mỗi sớm mai." },
  { id: 827, content: "Tộc trưởng làm đầu krog đau trong đêm tối." },
  { id: 828, content: "Tộc trưởng làm đầu krog đau bên bờ suối." },
  { id: 829, content: "Tộc trưởng làm đầu krog đau dưới gốc cây." },
  { id: 830, content: "Tộc trưởng làm đầu krog đau khi đói lòng." },
  { id: 831, content: "Tộc trưởng làm đầu krog đau suốt cuộc đời." },
  { id: 832, content: "Tộc trưởng mang lại niềm vui khi bão về." },
  { id: 833, content: "Tộc trưởng mang lại niềm vui giữa rừng sâu." },
  { id: 834, content: "Tộc trưởng mang lại niềm vui vào mùa đông." },
  { id: 835, content: "Tộc trưởng mang lại niềm vui sau cơn mưa." },
  { id: 836, content: "Tộc trưởng mang lại niềm vui mỗi sớm mai." },
  { id: 837, content: "Tộc trưởng mang lại niềm vui trong đêm tối." },
  { id: 838, content: "Tộc trưởng mang lại niềm vui bên bờ suối." },
  { id: 839, content: "Tộc trưởng mang lại niềm vui dưới gốc cây." },
  { id: 840, content: "Tộc trưởng mang lại niềm vui khi đói lòng." },
  { id: 841, content: "Tộc trưởng mang lại niềm vui suốt cuộc đời." },
  { id: 842, content: "Tộc trưởng xua tan bóng đêm khi bão về." },
  { id: 843, content: "Tộc trưởng xua tan bóng đêm giữa rừng sâu." },
  { id: 844, content: "Tộc trưởng xua tan bóng đêm vào mùa đông." },
  { id: 845, content: "Tộc trưởng xua tan bóng đêm sau cơn mưa." },
  { id: 846, content: "Tộc trưởng xua tan bóng đêm mỗi sớm mai." },
  { id: 847, content: "Tộc trưởng xua tan bóng đêm trong đêm tối." },
  { id: 848, content: "Tộc trưởng xua tan bóng đêm bên bờ suối." },
  { id: 849, content: "Tộc trưởng xua tan bóng đêm dưới gốc cây." },
  { id: 850, content: "Tộc trưởng xua tan bóng đêm khi đói lòng." },
  { id: 851, content: "Tộc trưởng xua tan bóng đêm suốt cuộc đời." },
  { id: 852, content: "Người thợ săn đừng vứt bỏ khi bão về." },
  { id: 853, content: "Người thợ săn đừng vứt bỏ giữa rừng sâu." },
  { id: 854, content: "Người thợ săn đừng vứt bỏ vào mùa đông." },
  { id: 855, content: "Người thợ săn đừng vứt bỏ sau cơn mưa." },
  { id: 856, content: "Người thợ săn đừng vứt bỏ mỗi sớm mai." },
  { id: 857, content: "Người thợ săn đừng vứt bỏ trong đêm tối." },
  { id: 858, content: "Người thợ săn đừng vứt bỏ bên bờ suối." },
  { id: 859, content: "Người thợ săn đừng vứt bỏ dưới gốc cây." },
  { id: 860, content: "Người thợ săn đừng vứt bỏ khi đói lòng." },
  { id: 861, content: "Người thợ săn đừng vứt bỏ suốt cuộc đời." },
  { id: 862, content: "Người thợ săn hãy trân trọng khi bão về." },
  { id: 863, content: "Người thợ săn hãy trân trọng giữa rừng sâu." },
  { id: 864, content: "Người thợ săn hãy trân trọng vào mùa đông." },
  { id: 865, content: "Người thợ săn hãy trân trọng sau cơn mưa." },
  { id: 866, content: "Người thợ săn hãy trân trọng mỗi sớm mai." },
  { id: 867, content: "Người thợ săn hãy trân trọng trong đêm tối." },
  { id: 868, content: "Người thợ săn hãy trân trọng bên bờ suối." },
  { id: 869, content: "Người thợ săn hãy trân trọng dưới gốc cây." },
  { id: 870, content: "Người thợ săn hãy trân trọng khi đói lòng." },
  { id: 871, content: "Người thợ săn hãy trân trọng suốt cuộc đời." },
  { id: 872, content: "Người thợ săn chớ coi thường khi bão về." },
  { id: 873, content: "Người thợ săn chớ coi thường giữa rừng sâu." },
  { id: 874, content: "Người thợ săn chớ coi thường vào mùa đông." },
  { id: 875, content: "Người thợ săn chớ coi thường sau cơn mưa." },
  { id: 876, content: "Người thợ săn chớ coi thường mỗi sớm mai." },
  { id: 877, content: "Người thợ săn chớ coi thường trong đêm tối." },
  { id: 878, content: "Người thợ săn chớ coi thường bên bờ suối." },
  { id: 879, content: "Người thợ săn chớ coi thường dưới gốc cây." },
  { id: 880, content: "Người thợ săn chớ coi thường khi đói lòng." },
  { id: 881, content: "Người thợ săn chớ coi thường suốt cuộc đời." },
  { id: 882, content: "Người thợ săn cần được giữ gìn khi bão về." },
  { id: 883, content: "Người thợ săn cần được giữ gìn giữa rừng sâu." },
  { id: 884, content: "Người thợ săn cần được giữ gìn vào mùa đông." },
  { id: 885, content: "Người thợ săn cần được giữ gìn sau cơn mưa." },
  { id: 886, content: "Người thợ săn cần được giữ gìn mỗi sớm mai." },
  { id: 887, content: "Người thợ săn cần được giữ gìn trong đêm tối." },
  { id: 888, content: "Người thợ săn cần được giữ gìn bên bờ suối." },
  { id: 889, content: "Người thợ săn cần được giữ gìn dưới gốc cây." },
  { id: 890, content: "Người thợ săn cần được giữ gìn khi đói lòng." },
  { id: 891, content: "Người thợ săn cần được giữ gìn suốt cuộc đời." },
  { id: 892, content: "Người thợ săn giúp krog ấm lòng khi bão về." },
  { id: 893, content: "Người thợ săn giúp krog ấm lòng giữa rừng sâu." },
  { id: 894, content: "Người thợ săn giúp krog ấm lòng vào mùa đông." },
  { id: 895, content: "Người thợ săn giúp krog ấm lòng sau cơn mưa." },
  { id: 896, content: "Người thợ săn giúp krog ấm lòng mỗi sớm mai." },
  { id: 897, content: "Người thợ săn giúp krog ấm lòng trong đêm tối." },
  { id: 898, content: "Người thợ săn giúp krog ấm lòng bên bờ suối." },
  { id: 899, content: "Người thợ săn giúp krog ấm lòng dưới gốc cây." },
  { id: 900, content: "Người thợ săn giúp krog ấm lòng khi đói lòng." },
  { id: 901, content: "Người thợ săn giúp krog ấm lòng suốt cuộc đời." },
  { id: 902, content: "Người thợ săn nuôi sống krog khi bão về." },
  { id: 903, content: "Người thợ săn nuôi sống krog giữa rừng sâu." },
  { id: 904, content: "Người thợ săn nuôi sống krog vào mùa đông." },
  { id: 905, content: "Người thợ săn nuôi sống krog sau cơn mưa." },
  { id: 906, content: "Người thợ săn nuôi sống krog mỗi sớm mai." },
  { id: 907, content: "Người thợ săn nuôi sống krog trong đêm tối." },
  { id: 908, content: "Người thợ săn nuôi sống krog bên bờ suối." },
  { id: 909, content: "Người thợ săn nuôi sống krog dưới gốc cây." },
  { id: 910, content: "Người thợ săn nuôi sống krog khi đói lòng." },
  { id: 911, content: "Người thợ săn nuôi sống krog suốt cuộc đời." },
  { id: 912, content: "Người thợ săn dạy krog bài học khi bão về." },
  { id: 913, content: "Người thợ săn dạy krog bài học giữa rừng sâu." },
  { id: 914, content: "Người thợ săn dạy krog bài học vào mùa đông." },
  { id: 915, content: "Người thợ săn dạy krog bài học sau cơn mưa." },
  { id: 916, content: "Người thợ săn dạy krog bài học mỗi sớm mai." },
  { id: 917, content: "Người thợ săn dạy krog bài học trong đêm tối." },
  { id: 918, content: "Người thợ săn dạy krog bài học bên bờ suối." },
  { id: 919, content: "Người thợ săn dạy krog bài học dưới gốc cây." },
  { id: 920, content: "Người thợ săn dạy krog bài học khi đói lòng." },
  { id: 921, content: "Người thợ săn dạy krog bài học suốt cuộc đời." },
  { id: 922, content: "Người thợ săn làm đầu krog đau khi bão về." },
  { id: 923, content: "Người thợ săn làm đầu krog đau giữa rừng sâu." },
  { id: 924, content: "Người thợ săn làm đầu krog đau vào mùa đông." },
  { id: 925, content: "Người thợ săn làm đầu krog đau sau cơn mưa." },
  { id: 926, content: "Người thợ săn làm đầu krog đau mỗi sớm mai." },
  { id: 927, content: "Người thợ săn làm đầu krog đau trong đêm tối." },
  { id: 928, content: "Người thợ săn làm đầu krog đau bên bờ suối." },
  { id: 929, content: "Người thợ săn làm đầu krog đau dưới gốc cây." },
  { id: 930, content: "Người thợ săn làm đầu krog đau khi đói lòng." },
  { id: 931, content: "Người thợ săn làm đầu krog đau suốt cuộc đời." },
  { id: 932, content: "Người thợ săn mang lại niềm vui khi bão về." },
  { id: 933, content: "Người thợ săn mang lại niềm vui giữa rừng sâu." },
  { id: 934, content: "Người thợ săn mang lại niềm vui vào mùa đông." },
  { id: 935, content: "Người thợ săn mang lại niềm vui sau cơn mưa." },
  { id: 936, content: "Người thợ săn mang lại niềm vui mỗi sớm mai." },
  { id: 937, content: "Người thợ săn mang lại niềm vui trong đêm tối." },
  { id: 938, content: "Người thợ săn mang lại niềm vui bên bờ suối." },
  { id: 939, content: "Người thợ săn mang lại niềm vui dưới gốc cây." },
  { id: 940, content: "Người thợ săn mang lại niềm vui khi đói lòng." },
  { id: 941, content: "Người thợ săn mang lại niềm vui suốt cuộc đời." },
  { id: 942, content: "Người thợ săn xua tan bóng đêm khi bão về." },
  { id: 943, content: "Người thợ săn xua tan bóng đêm giữa rừng sâu." },
  { id: 944, content: "Người thợ săn xua tan bóng đêm vào mùa đông." },
  { id: 945, content: "Người thợ săn xua tan bóng đêm sau cơn mưa." },
  { id: 946, content: "Người thợ săn xua tan bóng đêm mỗi sớm mai." },
  { id: 947, content: "Người thợ săn xua tan bóng đêm trong đêm tối." },
  { id: 948, content: "Người thợ săn xua tan bóng đêm bên bờ suối." },
  { id: 949, content: "Người thợ săn xua tan bóng đêm dưới gốc cây." },
  { id: 950, content: "Người thợ săn xua tan bóng đêm khi đói lòng." },
  { id: 951, content: "Người thợ săn xua tan bóng đêm suốt cuộc đời." },
  { id: 952, content: "Con hổ già đừng vứt bỏ khi bão về." },
  { id: 953, content: "Con hổ già đừng vứt bỏ giữa rừng sâu." },
  { id: 954, content: "Con hổ già đừng vứt bỏ vào mùa đông." },
  { id: 955, content: "Con hổ già đừng vứt bỏ sau cơn mưa." },
  { id: 956, content: "Con hổ già đừng vứt bỏ mỗi sớm mai." },
  { id: 957, content: "Con hổ già đừng vứt bỏ trong đêm tối." },
  { id: 958, content: "Con hổ già đừng vứt bỏ bên bờ suối." },
  { id: 959, content: "Con hổ già đừng vứt bỏ dưới gốc cây." },
  { id: 960, content: "Con hổ già đừng vứt bỏ khi đói lòng." },
  { id: 961, content: "Con hổ già đừng vứt bỏ suốt cuộc đời." },
  { id: 962, content: "Con hổ già hãy trân trọng khi bão về." },
  { id: 963, content: "Con hổ già hãy trân trọng giữa rừng sâu." },
  { id: 964, content: "Con hổ già hãy trân trọng vào mùa đông." },
  { id: 965, content: "Con hổ già hãy trân trọng sau cơn mưa." },
  { id: 966, content: "Con hổ già hãy trân trọng mỗi sớm mai." },
  { id: 967, content: "Con hổ già hãy trân trọng trong đêm tối." },
  { id: 968, content: "Con hổ già hãy trân trọng bên bờ suối." },
  { id: 969, content: "Con hổ già hãy trân trọng dưới gốc cây." },
  { id: 970, content: "Con hổ già hãy trân trọng khi đói lòng." },
  { id: 971, content: "Con hổ già hãy trân trọng suốt cuộc đời." },
  { id: 972, content: "Con hổ già chớ coi thường khi bão về." },
  { id: 973, content: "Con hổ già chớ coi thường giữa rừng sâu." },
  { id: 974, content: "Con hổ già chớ coi thường vào mùa đông." },
  { id: 975, content: "Con hổ già chớ coi thường sau cơn mưa." },
  { id: 976, content: "Con hổ già chớ coi thường mỗi sớm mai." },
  { id: 977, content: "Con hổ già chớ coi thường trong đêm tối." },
  { id: 978, content: "Con hổ già chớ coi thường bên bờ suối." },
  { id: 979, content: "Con hổ già chớ coi thường dưới gốc cây." },
  { id: 980, content: "Con hổ già chớ coi thường khi đói lòng." },
  { id: 981, content: "Con hổ già chớ coi thường suốt cuộc đời." },
  { id: 982, content: "Con hổ già cần được giữ gìn khi bão về." },
  { id: 983, content: "Con hổ già cần được giữ gìn giữa rừng sâu." },
  { id: 984, content: "Con hổ già cần được giữ gìn vào mùa đông." },
  { id: 985, content: "Con hổ già cần được giữ gìn sau cơn mưa." },
  { id: 986, content: "Con hổ già cần được giữ gìn mỗi sớm mai." },
  { id: 987, content: "Con hổ già cần được giữ gìn trong đêm tối." },
  { id: 988, content: "Con hổ già cần được giữ gìn bên bờ suối." },
  { id: 989, content: "Con hổ già cần được giữ gìn dưới gốc cây." },
  { id: 990, content: "Con hổ già cần được giữ gìn khi đói lòng." },
  { id: 991, content: "Con hổ già cần được giữ gìn suốt cuộc đời." },
  { id: 992, content: "Con hổ già giúp krog ấm lòng khi bão về." },
  { id: 993, content: "Con hổ già giúp krog ấm lòng giữa rừng sâu." },
  { id: 994, content: "Con hổ già giúp krog ấm lòng vào mùa đông." },
  { id: 995, content: "Con hổ già giúp krog ấm lòng sau cơn mưa." },
  { id: 996, content: "Con hổ già giúp krog ấm lòng mỗi sớm mai." },
  { id: 997, content: "Con hổ già giúp krog ấm lòng trong đêm tối." },
  { id: 998, content: "Con hổ già giúp krog ấm lòng bên bờ suối." },
  { id: 999, content: "Con hổ già giúp krog ấm lòng dưới gốc cây." },
  { id: 1000, content: "Con hổ già giúp krog ấm lòng khi đói lòng." }];

export const KROG_DICTIONARY: { [key: string]: string } = {
  "đi làm": "vác rìu đi săn bắn 🪓",
  "dilam": "vác rìu đi săn bắn 🪓",
  "làm việc": "mài rìu bẩy đá 🪨",
  "lương": "vỏ sò tươi 🐚",
  "tiền": "vỏ sò lấp lánh 🐚",
  "sếp": "tộc trưởng hung dữ 👹",
  "quản lý": "krog giám sát 👺",
  "đồng nghiệp": "gã chung hang 🪵",
  "báo cáo": "vẽ lên đá nộp bộ tộc 📊",
  "họp": "quây quanh đống lửa hú hét 🔥",
  "meeting": "quây quanh đống lửa hú hét 🔥",
  "stress": "đầu Krog bốc khói núi lửa 🔥",
  "áp lực": "đá núi đè trĩu vai 🏔️",
  "mệt": "tay bủn rủn, lưng đau nhừ 🪵",
  "met": "tay bủn rủn, lưng đau nhừ 🪵",
  "deadline": "thú dữ đuổi cắn sau mông 🦖",
  "khách hàng": "bộ tộc khó tính bên kia sông 🦧",
  "máy tính": "phiến đá lấp lánh phát sáng 💻",
  "điện thoại": "phiến đá nhỏ soi gương 📱",
  "internet": "mạng nhện ma pháp lơ lửng 🕸️",
  "facebook": "bản tin lá rụng đầu hang 🍂",
  "tiktok": "múa lửa mười giây 🕺",
  "bug": "con sâu đục gỗ sồi 🐛",
  "code": "gõ đá khắc chữ cổ ✍️",
  "lập trình": "đục đá đun nước 🪓",
  "dev": "gã thích đục đá 🪵",
  "người yêu": "bạn chung hang sưởi ấm 🌅",
  "bạn gái": "bạn chung hang sưởi ấm 🌅",
  "bạn trai": "bạn chung hang đi hái lượm 🌾",
  "độc thân": "lủi thủi săn hươu cô đơn 🦌",
  "vợ": "nữ chủ hang vác chày dọa nạt 👩‍🎨",
  "chồng": "nam chủ hang chuyên ngủ ngày 🛌",
  "nhà": "hang đá trú bão 🌋",
  "xe máy": "ngựa sắt khè ra khói xám 🏍️",
  "ô tô": "bốn tảng đá quay tròn bon bon 🚗",
  "bia": "nước men lúa mạch gây líu lưỡi 🍺",
  "rượu": "nước quả dại cay xè đầu lưỡi 🍷",
  "cà phê": "nước hạt đen đắng cho khỏi ngủ ngáy ☕",
  "cafe": "nước hạt đen đắng cho khỏi ngủ ngáy ☕"
};
